create table if not exists config (key text primary key not null, value blob);
create table if not exists followers (peerID text primary key not null, proof blob);
create table if not exists following (peerID text primary key not null);
create table if not exists offlinemessages (url text primary key not null, timestamp integer, message blob);
create table if not exists pointers (pointerID text primary key not null, key text, address text, cancelID text, purpose integer, timestamp integer);
create table if not exists keys (scriptAddress text primary key not null, purpose integer, keyIndex integer, used integer, key text);
create table if not exists utxos (outpoint text primary key not null, value integer, height integer, scriptPubKey text, watchOnly integer);
create table if not exists stxos (outpoint text primary key not null, value integer, height integer, scriptPubKey text, watchOnly integer, spendHeight integer, spendTxid text);
create table if not exists txns (txid text primary key not null, value integer, height integer, timestamp integer, watchOnly integer, tx blob);
create table if not exists txmetadata (txid text primary key not null, address text, memo text, orderID text, thumbnail text, canBumpFee integer);
create table if not exists inventory (invID text primary key not null, slug text, variantIndex integer, count integer);
create index if not exists index_inventory on inventory (slug);
create table if not exists purchases (orderID text primary key not null, contract blob, state integer, read integer, timestamp integer, total integer, thumbnail text, vendorID text, vendorBlockchainID text, title text, shippingName text, shippingAddress text, paymentAddr text, funded integer, transactions blob);
create index if not exists index_purchases on purchases (paymentAddr, timestamp);
create table if not exists sales (orderID text primary key not null, contract blob, state integer, read integer, timestamp integer, total integer, thumbnail text, buyerID text, buyerBlockchainID text, title text, shippingName text, shippingAddress text, paymentAddr text, funded integer, transactions blob);
create index if not exists index_sales on sales (paymentAddr, timestamp);
create table if not exists watchedscripts (scriptPubKey text primary key not null);
create table if not exists cases (caseID text primary key not null, buyerContract blob, vendorContract blob, buyerValidationErrors blob, vendorValidationErrors blob, buyerPayoutAddress text, vendorPayoutAddress text, buyerOutpoints blob, vendorOutpoints blob, state integer, read integer, timestamp integer, buyerOpened integer, claim text, disputeResolution blob);
create index if not exists index_cases on cases (timestamp);
create table if not exists chat (messageID text primary key not null, peerID text, subject text, message text, read integer, timestamp integer, outgoing integer);
create index if not exists index_chat on chat (peerID, subject, read, timestamp);
create table if not exists notifications (notifID text primary key not null, serializedNotification blob, type text, timestamp integer, read integer);
create index if not exists index_notifications on notifications (read, type, timestamp);
create table if not exists coupons (slug text, code text, hash text);
create index if not exists index_coupons on coupons (slug);
create table if not exists moderatedstores (peerID text primary key not null);