FROM openbazaar/server-qa:0.10

RUN go get -u github.com/gogo/protobuf/proto \
              github.com/golang/protobuf/protoc-gen-go \
              github.com/icrowley/fake \
              github.com/derekparker/delve/cmd/dlv \
              github.com/tools/godep

RUN cd /go/src/github.com/golang/protobuf && \
    git checkout tags/v1.2.0 -b v1.2.0 && \
    cd protoc-gen-go && \
    go install

RUN curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b $GOPATH/bin v1.15.0

WORKDIR /go/src/github.com/OpenBazaar/openbazaar-go

COPY . .

ENTRYPOINT ["/bin/bash"]
