FROM golang:1.11
VOLUME /var/lib/openbazaar

RUN apt-get -y update
RUN apt-get -y install software-properties-common
RUN apt-get install -yq zlib1g-dev libssl-dev unzip
RUN apt-get install -y python3 python3-pip

COPY ./qa/requirements.txt ./requirements.txt

RUN python3 -m pip install --upgrade pip && \
    python3 -m pip install -r requirements.txt && \
    wget https://bitcoin.org/bin/bitcoin-core-0.16.3/bitcoin-0.16.3-x86_64-linux-gnu.tar.gz && \
    tar -xvzf bitcoin-0.16.3-x86_64-linux-gnu.tar.gz -C /opt

RUN wget https://github.com/google/protobuf/releases/download/v3.6.0/protoc-3.6.0-linux-x86_64.zip && \
    unzip ./protoc-3.6.0-linux-x86_64.zip -x readme.txt && \
    mv ./include/* /usr/local/include/ && \
    mv ./bin/protoc /usr/local/bin/ && \
    rm -rf ./include ./bin

RUN go get -u github.com/gogo/protobuf/proto \
              github.com/golang/protobuf/protoc-gen-go \
              github.com/icrowley/fake \
              github.com/derekparker/delve/cmd/dlv \
              github.com/tools/godep

RUN cd /go/src/github.com/golang/protobuf && \
    git checkout tags/v1.2.0 -b v1.2.0 && \
    cd protoc-gen-go && \
    go install

RUN curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b $GOPATH/bin v1.15.0

WORKDIR /go/src/github.com/OpenBazaar/openbazaar-go

COPY . .

ENTRYPOINT ["/bin/bash"]
