// Objective-C API for talking to github.com/OpenBazaar/openbazaar-go Go package.
//   gobind -lang=objc github.com/OpenBazaar/openbazaar-go
//
// File is generated by gobind. Do not edit.

#ifndef __Openbazaar_H__
#define __Openbazaar_H__

@import Foundation;
#include "Universe.objc.h"


@class OpenbazaarOpenBazaar;

@interface OpenbazaarOpenBazaar : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
- (void)helloWorld;
@end

#endif
