// Code generated by protoc-gen-go.
// source: api.proto
// DO NOT EDIT!

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	api.proto
	contracts.proto
	countrycodes.proto
	message.proto
	moderator.proto
	orders.proto
	profile.proto

It has these top-level messages:
	Coupon
	OrderRespApi
	CaseRespApi
	TransactionRecord
	PeerAndProfile
	PeerAndProfileWithID
	RatingWithID
	RicardianContract
	Listing
	Order
	OrderConfirmation
	OrderReject
	RatingSignature
	BitcoinSignature
	OrderFulfillment
	OrderCompletion
	Rating
	Dispute
	DisputeResolution
	Outpoint
	Refund
	ID
	Signature
	SignedListing
	Message
	Envelope
	Chat
	Moderator
	DisputeUpdate
	Profile
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Coupon struct {
	Hash string `protobuf:"bytes,1,opt,name=hash" json:"hash,omitempty"`
	Code string `protobuf:"bytes,2,opt,name=code" json:"code,omitempty"`
}

func (m *Coupon) Reset()                    { *m = Coupon{} }
func (m *Coupon) String() string            { return proto.CompactTextString(m) }
func (*Coupon) ProtoMessage()               {}
func (*Coupon) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Coupon) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *Coupon) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type OrderRespApi struct {
	Contract     *RicardianContract   `protobuf:"bytes,1,opt,name=contract" json:"contract,omitempty"`
	State        OrderState           `protobuf:"varint,2,opt,name=state,enum=OrderState" json:"state,omitempty"`
	Read         bool                 `protobuf:"varint,3,opt,name=read" json:"read,omitempty"`
	Funded       bool                 `protobuf:"varint,4,opt,name=funded" json:"funded,omitempty"`
	Transactions []*TransactionRecord `protobuf:"bytes,5,rep,name=transactions" json:"transactions,omitempty"`
}

func (m *OrderRespApi) Reset()                    { *m = OrderRespApi{} }
func (m *OrderRespApi) String() string            { return proto.CompactTextString(m) }
func (*OrderRespApi) ProtoMessage()               {}
func (*OrderRespApi) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *OrderRespApi) GetContract() *RicardianContract {
	if m != nil {
		return m.Contract
	}
	return nil
}

func (m *OrderRespApi) GetState() OrderState {
	if m != nil {
		return m.State
	}
	return OrderState_PENDING
}

func (m *OrderRespApi) GetRead() bool {
	if m != nil {
		return m.Read
	}
	return false
}

func (m *OrderRespApi) GetFunded() bool {
	if m != nil {
		return m.Funded
	}
	return false
}

func (m *OrderRespApi) GetTransactions() []*TransactionRecord {
	if m != nil {
		return m.Transactions
	}
	return nil
}

type CaseRespApi struct {
	Timestamp                      *google_protobuf.Timestamp `protobuf:"bytes,1,opt,name=timestamp" json:"timestamp,omitempty"`
	BuyerContract                  *RicardianContract         `protobuf:"bytes,2,opt,name=buyerContract" json:"buyerContract,omitempty"`
	VendorContract                 *RicardianContract         `protobuf:"bytes,3,opt,name=vendorContract" json:"vendorContract,omitempty"`
	BuyerContractValidationErrors  []string                   `protobuf:"bytes,4,rep,name=buyerContractValidationErrors" json:"buyerContractValidationErrors,omitempty"`
	VendorContractValidationErrors []string                   `protobuf:"bytes,5,rep,name=vendorContractValidationErrors" json:"vendorContractValidationErrors,omitempty"`
	State                          OrderState                 `protobuf:"varint,6,opt,name=state,enum=OrderState" json:"state,omitempty"`
	Read                           bool                       `protobuf:"varint,7,opt,name=read" json:"read,omitempty"`
	BuyerOpened                    bool                       `protobuf:"varint,8,opt,name=buyerOpened" json:"buyerOpened,omitempty"`
	Claim                          string                     `protobuf:"bytes,9,opt,name=claim" json:"claim,omitempty"`
	Resolution                     *DisputeResolution         `protobuf:"bytes,10,opt,name=resolution" json:"resolution,omitempty"`
}

func (m *CaseRespApi) Reset()                    { *m = CaseRespApi{} }
func (m *CaseRespApi) String() string            { return proto.CompactTextString(m) }
func (*CaseRespApi) ProtoMessage()               {}
func (*CaseRespApi) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CaseRespApi) GetTimestamp() *google_protobuf.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *CaseRespApi) GetBuyerContract() *RicardianContract {
	if m != nil {
		return m.BuyerContract
	}
	return nil
}

func (m *CaseRespApi) GetVendorContract() *RicardianContract {
	if m != nil {
		return m.VendorContract
	}
	return nil
}

func (m *CaseRespApi) GetBuyerContractValidationErrors() []string {
	if m != nil {
		return m.BuyerContractValidationErrors
	}
	return nil
}

func (m *CaseRespApi) GetVendorContractValidationErrors() []string {
	if m != nil {
		return m.VendorContractValidationErrors
	}
	return nil
}

func (m *CaseRespApi) GetState() OrderState {
	if m != nil {
		return m.State
	}
	return OrderState_PENDING
}

func (m *CaseRespApi) GetRead() bool {
	if m != nil {
		return m.Read
	}
	return false
}

func (m *CaseRespApi) GetBuyerOpened() bool {
	if m != nil {
		return m.BuyerOpened
	}
	return false
}

func (m *CaseRespApi) GetClaim() string {
	if m != nil {
		return m.Claim
	}
	return ""
}

func (m *CaseRespApi) GetResolution() *DisputeResolution {
	if m != nil {
		return m.Resolution
	}
	return nil
}

type TransactionRecord struct {
	Txid          string `protobuf:"bytes,1,opt,name=txid" json:"txid,omitempty"`
	Value         int64  `protobuf:"varint,2,opt,name=value" json:"value,omitempty"`
	Confirmations uint32 `protobuf:"varint,3,opt,name=confirmations" json:"confirmations,omitempty"`
}

func (m *TransactionRecord) Reset()                    { *m = TransactionRecord{} }
func (m *TransactionRecord) String() string            { return proto.CompactTextString(m) }
func (*TransactionRecord) ProtoMessage()               {}
func (*TransactionRecord) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *TransactionRecord) GetTxid() string {
	if m != nil {
		return m.Txid
	}
	return ""
}

func (m *TransactionRecord) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *TransactionRecord) GetConfirmations() uint32 {
	if m != nil {
		return m.Confirmations
	}
	return 0
}

type PeerAndProfile struct {
	PeerId  string   `protobuf:"bytes,1,opt,name=peerId" json:"peerId,omitempty"`
	Profile *Profile `protobuf:"bytes,2,opt,name=profile" json:"profile,omitempty"`
}

func (m *PeerAndProfile) Reset()                    { *m = PeerAndProfile{} }
func (m *PeerAndProfile) String() string            { return proto.CompactTextString(m) }
func (*PeerAndProfile) ProtoMessage()               {}
func (*PeerAndProfile) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *PeerAndProfile) GetPeerId() string {
	if m != nil {
		return m.PeerId
	}
	return ""
}

func (m *PeerAndProfile) GetProfile() *Profile {
	if m != nil {
		return m.Profile
	}
	return nil
}

type PeerAndProfileWithID struct {
	Id      string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	PeerId  string   `protobuf:"bytes,2,opt,name=peerId" json:"peerId,omitempty"`
	Profile *Profile `protobuf:"bytes,3,opt,name=profile" json:"profile,omitempty"`
}

func (m *PeerAndProfileWithID) Reset()                    { *m = PeerAndProfileWithID{} }
func (m *PeerAndProfileWithID) String() string            { return proto.CompactTextString(m) }
func (*PeerAndProfileWithID) ProtoMessage()               {}
func (*PeerAndProfileWithID) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *PeerAndProfileWithID) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PeerAndProfileWithID) GetPeerId() string {
	if m != nil {
		return m.PeerId
	}
	return ""
}

func (m *PeerAndProfileWithID) GetProfile() *Profile {
	if m != nil {
		return m.Profile
	}
	return nil
}

type RatingWithID struct {
	Id       string  `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	RatingId string  `protobuf:"bytes,2,opt,name=ratingId" json:"ratingId,omitempty"`
	Rating   *Rating `protobuf:"bytes,3,opt,name=rating" json:"rating,omitempty"`
}

func (m *RatingWithID) Reset()                    { *m = RatingWithID{} }
func (m *RatingWithID) String() string            { return proto.CompactTextString(m) }
func (*RatingWithID) ProtoMessage()               {}
func (*RatingWithID) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *RatingWithID) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *RatingWithID) GetRatingId() string {
	if m != nil {
		return m.RatingId
	}
	return ""
}

func (m *RatingWithID) GetRating() *Rating {
	if m != nil {
		return m.Rating
	}
	return nil
}

func init() {
	proto.RegisterType((*Coupon)(nil), "Coupon")
	proto.RegisterType((*OrderRespApi)(nil), "OrderRespApi")
	proto.RegisterType((*CaseRespApi)(nil), "CaseRespApi")
	proto.RegisterType((*TransactionRecord)(nil), "TransactionRecord")
	proto.RegisterType((*PeerAndProfile)(nil), "PeerAndProfile")
	proto.RegisterType((*PeerAndProfileWithID)(nil), "PeerAndProfileWithID")
	proto.RegisterType((*RatingWithID)(nil), "RatingWithID")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 546 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x84, 0x53, 0x5b, 0x8b, 0x13, 0x31,
	0x14, 0xa6, 0x9d, 0x5e, 0x4f, 0x2f, 0x62, 0x58, 0x64, 0x28, 0xe8, 0xd6, 0xc1, 0x87, 0x3e, 0xcd,
	0x4a, 0x05, 0x59, 0x7c, 0x5b, 0x5b, 0x85, 0x05, 0x61, 0x97, 0xb8, 0x28, 0xe8, 0x53, 0x3a, 0x49,
	0xdb, 0xc0, 0x74, 0x12, 0x92, 0xcc, 0xa2, 0x3f, 0xd0, 0xbf, 0xe3, 0x6f, 0x90, 0x5c, 0xa6, 0xed,
	0xb8, 0xd6, 0x7d, 0x3b, 0xe7, 0x3b, 0x5f, 0xbe, 0x73, 0x0d, 0xf4, 0x89, 0xe4, 0xa9, 0x54, 0xc2,
	0x88, 0xc9, 0x93, 0x4c, 0x14, 0x46, 0x91, 0xcc, 0xe8, 0x00, 0x0c, 0x85, 0xa2, 0x4c, 0x55, 0xde,
	0x48, 0x2a, 0xb1, 0xe6, 0x39, 0x0b, 0xee, 0xf9, 0x46, 0x88, 0x4d, 0xce, 0x2e, 0x9c, 0xb7, 0x2a,
	0xd7, 0x17, 0x86, 0xef, 0x98, 0x36, 0x64, 0x27, 0x3d, 0x21, 0x79, 0x0d, 0x9d, 0x85, 0x28, 0xa5,
	0x28, 0x10, 0x82, 0xd6, 0x96, 0xe8, 0x6d, 0xdc, 0x98, 0x36, 0x66, 0x7d, 0xec, 0x6c, 0x8b, 0x65,
	0x82, 0xb2, 0xb8, 0xe9, 0x31, 0x6b, 0x27, 0xbf, 0x1a, 0x30, 0xbc, 0xb1, 0x29, 0x31, 0xd3, 0xf2,
	0x4a, 0x72, 0x94, 0x42, 0xaf, 0xaa, 0xc9, 0x3d, 0x1e, 0xcc, 0x51, 0x8a, 0x79, 0x46, 0x14, 0xe5,
	0xa4, 0x58, 0x84, 0x08, 0xde, 0x73, 0xd0, 0x4b, 0x68, 0x6b, 0x43, 0x8c, 0x57, 0x1d, 0xcf, 0x07,
	0xa9, 0x53, 0xfb, 0x6c, 0x21, 0xec, 0x23, 0x36, 0xaf, 0x62, 0x84, 0xc6, 0xd1, 0xb4, 0x31, 0xeb,
	0x61, 0x67, 0xa3, 0x67, 0xd0, 0x59, 0x97, 0x05, 0x65, 0x34, 0x6e, 0x39, 0x34, 0x78, 0xe8, 0x2d,
	0x0c, 0x8d, 0x22, 0x85, 0x26, 0x99, 0xe1, 0xa2, 0xd0, 0x71, 0x7b, 0x1a, 0xb9, 0x12, 0xee, 0x0e,
	0x20, 0x66, 0x99, 0x50, 0x14, 0xd7, 0x78, 0xc9, 0xef, 0x08, 0x06, 0x0b, 0xa2, 0x59, 0xd5, 0xc6,
	0x25, 0xf4, 0xf7, 0xc3, 0x09, 0x7d, 0x4c, 0x52, 0x3f, 0xbe, 0xb4, 0x1a, 0x5f, 0x7a, 0x57, 0x31,
	0xf0, 0x81, 0x8c, 0x2e, 0x61, 0xb4, 0x2a, 0x7f, 0x32, 0x55, 0xf5, 0xea, 0x1a, 0xfb, 0xf7, 0x14,
	0xea, 0x44, 0xf4, 0x0e, 0xc6, 0xf7, 0xac, 0xa0, 0xe2, 0xf0, 0x34, 0x3a, 0xf9, 0xf4, 0x2f, 0x26,
	0x5a, 0xc2, 0xf3, 0x9a, 0xd8, 0x17, 0x92, 0x73, 0x4a, 0x6c, 0x6f, 0x1f, 0x94, 0x12, 0x4a, 0xc7,
	0xad, 0x69, 0x34, 0xeb, 0xe3, 0xff, 0x93, 0xd0, 0x47, 0x78, 0x51, 0xd7, 0x7d, 0x20, 0xd3, 0x76,
	0x32, 0x8f, 0xb0, 0x0e, 0x4b, 0xed, 0x3c, 0xba, 0xd4, 0xee, 0xd1, 0x52, 0xa7, 0x30, 0x70, 0xf5,
	0xdd, 0x48, 0x56, 0x30, 0x1a, 0xf7, 0x5c, 0xe8, 0x18, 0x42, 0x67, 0xd0, 0xce, 0x72, 0xc2, 0x77,
	0x71, 0xdf, 0xdd, 0xa0, 0x77, 0xd0, 0x1c, 0x40, 0x31, 0x2d, 0xf2, 0xd2, 0x96, 0x10, 0x43, 0x18,
	0xda, 0x92, 0x6b, 0x59, 0x1a, 0xbb, 0xd1, 0x10, 0xc1, 0x47, 0xac, 0x24, 0x83, 0xa7, 0x0f, 0x6e,
	0xc2, 0x16, 0x65, 0x7e, 0x70, 0x5a, 0x5d, 0xbd, 0xb5, 0x6d, 0xca, 0x7b, 0x92, 0x97, 0xfe, 0x40,
	0x23, 0xec, 0x1d, 0xf4, 0x0a, 0x46, 0x99, 0x28, 0xd6, 0x5c, 0xed, 0x88, 0x3f, 0x34, 0xbb, 0xaa,
	0x11, 0xae, 0x83, 0xc9, 0x27, 0x18, 0xdf, 0x32, 0xa6, 0xae, 0x0a, 0x7a, 0xeb, 0x3f, 0xa2, 0xbd,
	0x5b, 0xc9, 0x98, 0xba, 0xae, 0x72, 0x04, 0x0f, 0x25, 0xd0, 0x0d, 0x7f, 0x35, 0xdc, 0x4b, 0x2f,
	0x0d, 0x4f, 0x70, 0x15, 0x48, 0x56, 0x70, 0x56, 0x57, 0xfb, 0xca, 0xcd, 0xf6, 0x7a, 0x89, 0xc6,
	0xd0, 0xdc, 0xd7, 0xdc, 0xe4, 0xf4, 0x28, 0x47, 0xf3, 0x54, 0x8e, 0xe8, 0x54, 0x8e, 0xef, 0x30,
	0xc4, 0xc4, 0xf0, 0x62, 0x73, 0x42, 0x7b, 0x02, 0x3d, 0xe5, 0xe2, 0x7b, 0xf5, 0xbd, 0x8f, 0xce,
	0xa1, 0xe3, 0xed, 0x20, 0xdf, 0x4d, 0xbd, 0x14, 0x0e, 0xf0, 0xfb, 0xd6, 0xb7, 0xa6, 0x5c, 0xad,
	0x3a, 0xee, 0xff, 0xbc, 0xf9, 0x13, 0x00, 0x00, 0xff, 0xff, 0x42, 0x02, 0x8c, 0x34, 0xc7, 0x04,
	0x00, 0x00,
}
