// Code generated by protoc-gen-go.
// source: api.proto
// DO NOT EDIT!

/*
Package api is a generated protocol buffer package.

It is generated from these files:
	api.proto

It has these top-level messages:
	ListingReqApi
	ListingRespApi
	Inventory
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type ListingReqApi struct {
	Listing     *Listing     `protobuf:"bytes,1,opt,name=listing" json:"listing,omitempty"`
	Inventory   []*Inventory `protobuf:"bytes,2,rep,name=inventory" json:"inventory,omitempty"`
	CurrentSlug string       `protobuf:"bytes,3,opt,name=currentSlug" json:"currentSlug,omitempty"`
}

func (m *ListingReqApi) Reset()                    { *m = ListingReqApi{} }
func (m *ListingReqApi) String() string            { return proto.CompactTextString(m) }
func (*ListingReqApi) ProtoMessage()               {}
func (*ListingReqApi) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{0} }

func (m *ListingReqApi) GetListing() *Listing {
	if m != nil {
		return m.Listing
	}
	return nil
}

func (m *ListingReqApi) GetInventory() []*Inventory {
	if m != nil {
		return m.Inventory
	}
	return nil
}

type ListingRespApi struct {
	Contract  *RicardianContract `protobuf:"bytes,1,opt,name=contract" json:"contract,omitempty"`
	Inventory []*Inventory       `protobuf:"bytes,2,rep,name=inventory" json:"inventory,omitempty"`
}

func (m *ListingRespApi) Reset()                    { *m = ListingRespApi{} }
func (m *ListingRespApi) String() string            { return proto.CompactTextString(m) }
func (*ListingRespApi) ProtoMessage()               {}
func (*ListingRespApi) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{1} }

func (m *ListingRespApi) GetContract() *RicardianContract {
	if m != nil {
		return m.Contract
	}
	return nil
}

func (m *ListingRespApi) GetInventory() []*Inventory {
	if m != nil {
		return m.Inventory
	}
	return nil
}

type Inventory struct {
	Item  string `protobuf:"bytes,1,opt,name=item" json:"item,omitempty"`
	Count uint64 `protobuf:"varint,2,opt,name=count" json:"count,omitempty"`
}

func (m *Inventory) Reset()                    { *m = Inventory{} }
func (m *Inventory) String() string            { return proto.CompactTextString(m) }
func (*Inventory) ProtoMessage()               {}
func (*Inventory) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{2} }

func init() {
	proto.RegisterType((*ListingReqApi)(nil), "ListingReqApi")
	proto.RegisterType((*ListingRespApi)(nil), "ListingRespApi")
	proto.RegisterType((*Inventory)(nil), "Inventory")
}

var fileDescriptor5 = []byte{
	// 213 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x4c, 0x2c, 0xc8, 0xd4,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x97, 0xe2, 0x4f, 0xce, 0xcf, 0x2b, 0x29, 0x4a, 0x4c, 0x2e, 0x29,
	0x86, 0x08, 0x28, 0xd5, 0x73, 0xf1, 0xfa, 0x64, 0x16, 0x97, 0x64, 0xe6, 0xa5, 0x07, 0xa5, 0x16,
	0x3a, 0x16, 0x64, 0x0a, 0x29, 0x71, 0xb1, 0xe7, 0x40, 0x04, 0x24, 0x18, 0x15, 0x18, 0x35, 0xb8,
	0x8d, 0x38, 0xf4, 0x60, 0x0a, 0x60, 0x12, 0x42, 0x1a, 0x5c, 0x9c, 0x99, 0x79, 0x65, 0xa9, 0x79,
	0x25, 0xf9, 0x45, 0x95, 0x12, 0x4c, 0x0a, 0xcc, 0x40, 0x55, 0x5c, 0x7a, 0x9e, 0x30, 0x91, 0x20,
	0x84, 0xa4, 0x90, 0x02, 0x17, 0x77, 0x72, 0x69, 0x51, 0x11, 0x90, 0x17, 0x9c, 0x53, 0x9a, 0x2e,
	0xc1, 0x0c, 0x34, 0x91, 0x33, 0x08, 0x59, 0x48, 0x29, 0x8b, 0x8b, 0x0f, 0xee, 0x80, 0xe2, 0x02,
	0x90, 0x0b, 0xf4, 0xb8, 0x38, 0x60, 0xae, 0x84, 0x3a, 0x41, 0x48, 0x2f, 0x28, 0x33, 0x39, 0xb1,
	0x28, 0x25, 0x33, 0x31, 0xcf, 0x19, 0x2a, 0x13, 0x04, 0x57, 0x43, 0xbc, 0x6b, 0x94, 0x4c, 0xb9,
	0x38, 0xe1, 0xe2, 0x42, 0x42, 0x5c, 0x2c, 0x99, 0x25, 0xa9, 0xb9, 0x60, 0x2b, 0x38, 0x83, 0xc0,
	0x6c, 0x21, 0x11, 0x2e, 0xd6, 0xe4, 0xfc, 0xd2, 0xbc, 0x12, 0xa0, 0x31, 0x8c, 0x1a, 0x2c, 0x41,
	0x10, 0x4e, 0x12, 0x1b, 0x38, 0xa8, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x8c, 0xc0, 0x84,
	0x59, 0x48, 0x01, 0x00, 0x00,
}
