// Code generated by protoc-gen-go.
// source: contracts.proto
// DO NOT EDIT!

/*
Package contracts is a generated protocol buffer package.

It is generated from these files:
	contracts.proto

It has these top-level messages:
	RicardianContract
	Listing
	Order
	OrderConfirmation
	Rating
	Dispute
	DisputeResolution
	Refund
	ID
	Signatures
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type Listing_Metadata_CategorySub int32

const (
	Listing_Metadata_NA          Listing_Metadata_CategorySub = 0
	Listing_Metadata_FIXED_PRICE Listing_Metadata_CategorySub = 1
	Listing_Metadata_AUCTION     Listing_Metadata_CategorySub = 2
)

var Listing_Metadata_CategorySub_name = map[int32]string{
	0: "NA",
	1: "FIXED_PRICE",
	2: "AUCTION",
}
var Listing_Metadata_CategorySub_value = map[string]int32{
	"NA":          0,
	"FIXED_PRICE": 1,
	"AUCTION":     2,
}

func (x Listing_Metadata_CategorySub) String() string {
	return proto.EnumName(Listing_Metadata_CategorySub_name, int32(x))
}
func (Listing_Metadata_CategorySub) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor1, []int{1, 0, 0}
}

type Listing_Metadata_Category int32

const (
	Listing_Metadata_UNKNOWN       Listing_Metadata_Category = 0
	Listing_Metadata_PHYSICAL_GOOD Listing_Metadata_Category = 1
	Listing_Metadata_DIGITAL_GOOD  Listing_Metadata_Category = 2
	Listing_Metadata_SERVICE       Listing_Metadata_Category = 3
)

var Listing_Metadata_Category_name = map[int32]string{
	0: "UNKNOWN",
	1: "PHYSICAL_GOOD",
	2: "DIGITAL_GOOD",
	3: "SERVICE",
}
var Listing_Metadata_Category_value = map[string]int32{
	"UNKNOWN":       0,
	"PHYSICAL_GOOD": 1,
	"DIGITAL_GOOD":  2,
	"SERVICE":       3,
}

func (x Listing_Metadata_Category) String() string {
	return proto.EnumName(Listing_Metadata_Category_name, int32(x))
}
func (Listing_Metadata_Category) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor1, []int{1, 0, 1}
}

type Order_Payment_Method int32

const (
	Order_Payment_DIRECT    Order_Payment_Method = 0
	Order_Payment_MODERATED Order_Payment_Method = 1
)

var Order_Payment_Method_name = map[int32]string{
	0: "DIRECT",
	1: "MODERATED",
}
var Order_Payment_Method_value = map[string]int32{
	"DIRECT":    0,
	"MODERATED": 1,
}

func (x Order_Payment_Method) String() string {
	return proto.EnumName(Order_Payment_Method_name, int32(x))
}
func (Order_Payment_Method) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{2, 2, 0} }

type Signatures_Section int32

const (
	Signatures_LISTING            Signatures_Section = 0
	Signatures_ORDER              Signatures_Section = 1
	Signatures_ORDER_CONFIRMATION Signatures_Section = 2
	Signatures_RATING             Signatures_Section = 3
	Signatures_DISPUTE            Signatures_Section = 4
	Signatures_DISPUTE_RESOLUTION Signatures_Section = 5
	Signatures_REFUND             Signatures_Section = 6
)

var Signatures_Section_name = map[int32]string{
	0: "LISTING",
	1: "ORDER",
	2: "ORDER_CONFIRMATION",
	3: "RATING",
	4: "DISPUTE",
	5: "DISPUTE_RESOLUTION",
	6: "REFUND",
}
var Signatures_Section_value = map[string]int32{
	"LISTING":            0,
	"ORDER":              1,
	"ORDER_CONFIRMATION": 2,
	"RATING":             3,
	"DISPUTE":            4,
	"DISPUTE_RESOLUTION": 5,
	"REFUND":             6,
}

func (x Signatures_Section) String() string {
	return proto.EnumName(Signatures_Section_name, int32(x))
}
func (Signatures_Section) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{9, 0} }

type RicardianContract struct {
	VendorListings          []*Listing         `protobuf:"bytes,1,rep,name=vendorListings" json:"vendorListings,omitempty"`
	BuyerOrder              *Order             `protobuf:"bytes,2,opt,name=buyerOrder" json:"buyerOrder,omitempty"`
	VendorOrderConfirmation *OrderConfirmation `protobuf:"bytes,3,opt,name=vendorOrderConfirmation" json:"vendorOrderConfirmation,omitempty"`
	BuyerRating             *Rating            `protobuf:"bytes,4,opt,name=buyerRating" json:"buyerRating,omitempty"`
	Dispute                 *Dispute           `protobuf:"bytes,5,opt,name=dispute" json:"dispute,omitempty"`
	DisputeResolution       *DisputeResolution `protobuf:"bytes,6,opt,name=disputeResolution" json:"disputeResolution,omitempty"`
	Refund                  *Refund            `protobuf:"bytes,7,opt,name=refund" json:"refund,omitempty"`
	Signatures              []*Signatures      `protobuf:"bytes,8,rep,name=signatures" json:"signatures,omitempty"`
}

func (m *RicardianContract) Reset()                    { *m = RicardianContract{} }
func (m *RicardianContract) String() string            { return proto.CompactTextString(m) }
func (*RicardianContract) ProtoMessage()               {}
func (*RicardianContract) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *RicardianContract) GetVendorListings() []*Listing {
	if m != nil {
		return m.VendorListings
	}
	return nil
}

func (m *RicardianContract) GetBuyerOrder() *Order {
	if m != nil {
		return m.BuyerOrder
	}
	return nil
}

func (m *RicardianContract) GetVendorOrderConfirmation() *OrderConfirmation {
	if m != nil {
		return m.VendorOrderConfirmation
	}
	return nil
}

func (m *RicardianContract) GetBuyerRating() *Rating {
	if m != nil {
		return m.BuyerRating
	}
	return nil
}

func (m *RicardianContract) GetDispute() *Dispute {
	if m != nil {
		return m.Dispute
	}
	return nil
}

func (m *RicardianContract) GetDisputeResolution() *DisputeResolution {
	if m != nil {
		return m.DisputeResolution
	}
	return nil
}

func (m *RicardianContract) GetRefund() *Refund {
	if m != nil {
		return m.Refund
	}
	return nil
}

func (m *RicardianContract) GetSignatures() []*Signatures {
	if m != nil {
		return m.Signatures
	}
	return nil
}

type Listing struct {
	ListingName        string            `protobuf:"bytes,1,opt,name=listingName" json:"listingName,omitempty"`
	VendorID           *ID               `protobuf:"bytes,2,opt,name=vendorID" json:"vendorID,omitempty"`
	Metadata           *Listing_Metadata `protobuf:"bytes,3,opt,name=metadata" json:"metadata,omitempty"`
	Item               *Listing_Item     `protobuf:"bytes,4,opt,name=item" json:"item,omitempty"`
	Shipping           *Listing_Shipping `protobuf:"bytes,5,opt,name=shipping" json:"shipping,omitempty"`
	Moderators         []string          `protobuf:"bytes,6,rep,name=moderators" json:"moderators,omitempty"`
	TermsAndConditions string            `protobuf:"bytes,7,opt,name=termsAndConditions" json:"termsAndConditions,omitempty"`
	RefundPolicy       string            `protobuf:"bytes,8,opt,name=refundPolicy" json:"refundPolicy,omitempty"`
}

func (m *Listing) Reset()                    { *m = Listing{} }
func (m *Listing) String() string            { return proto.CompactTextString(m) }
func (*Listing) ProtoMessage()               {}
func (*Listing) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *Listing) GetVendorID() *ID {
	if m != nil {
		return m.VendorID
	}
	return nil
}

func (m *Listing) GetMetadata() *Listing_Metadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *Listing) GetItem() *Listing_Item {
	if m != nil {
		return m.Item
	}
	return nil
}

func (m *Listing) GetShipping() *Listing_Shipping {
	if m != nil {
		return m.Shipping
	}
	return nil
}

type Listing_Metadata struct {
	Version     uint32                       `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	Category    Listing_Metadata_Category    `protobuf:"varint,2,opt,name=category,enum=Listing_Metadata_Category" json:"category,omitempty"`
	CategorySub Listing_Metadata_CategorySub `protobuf:"varint,3,opt,name=categorySub,enum=Listing_Metadata_CategorySub" json:"categorySub,omitempty"`
	Expiry      uint64                       `protobuf:"varint,4,opt,name=expiry" json:"expiry,omitempty"`
}

func (m *Listing_Metadata) Reset()                    { *m = Listing_Metadata{} }
func (m *Listing_Metadata) String() string            { return proto.CompactTextString(m) }
func (*Listing_Metadata) ProtoMessage()               {}
func (*Listing_Metadata) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1, 0} }

type Listing_Item struct {
	Title          string                 `protobuf:"bytes,1,opt,name=title" json:"title,omitempty"`
	Description    string                 `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
	ProcessingTime string                 `protobuf:"bytes,3,opt,name=processingTime" json:"processingTime,omitempty"`
	PricePerUnit   *Listing_Price         `protobuf:"bytes,4,opt,name=pricePerUnit" json:"pricePerUnit,omitempty"`
	Nsfw           bool                   `protobuf:"varint,5,opt,name=nsfw" json:"nsfw,omitempty"`
	Tags           []string               `protobuf:"bytes,6,rep,name=tags" json:"tags,omitempty"`
	ImageHashes    []string               `protobuf:"bytes,7,rep,name=imageHashes" json:"imageHashes,omitempty"`
	SKU            string                 `protobuf:"bytes,8,opt,name=SKU,json=sKU" json:"SKU,omitempty"`
	Condition      string                 `protobuf:"bytes,9,opt,name=condition" json:"condition,omitempty"`
	Options        []*Listing_Item_Option `protobuf:"bytes,10,rep,name=options" json:"options,omitempty"`
}

func (m *Listing_Item) Reset()                    { *m = Listing_Item{} }
func (m *Listing_Item) String() string            { return proto.CompactTextString(m) }
func (*Listing_Item) ProtoMessage()               {}
func (*Listing_Item) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1, 1} }

func (m *Listing_Item) GetPricePerUnit() *Listing_Price {
	if m != nil {
		return m.PricePerUnit
	}
	return nil
}

func (m *Listing_Item) GetOptions() []*Listing_Item_Option {
	if m != nil {
		return m.Options
	}
	return nil
}

type Listing_Item_Option struct {
	Name        string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Description string   `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
	Values      []string `protobuf:"bytes,3,rep,name=values" json:"values,omitempty"`
}

func (m *Listing_Item_Option) Reset()                    { *m = Listing_Item_Option{} }
func (m *Listing_Item_Option) String() string            { return proto.CompactTextString(m) }
func (*Listing_Item_Option) ProtoMessage()               {}
func (*Listing_Item_Option) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1, 1, 0} }

type Listing_Shipping struct {
	Domestic          *Listing_Price                      `protobuf:"bytes,1,opt,name=domestic" json:"domestic,omitempty"`
	International     *Listing_Price                      `protobuf:"bytes,2,opt,name=international" json:"international,omitempty"`
	ShippingRegions   []CountryCode                       `protobuf:"varint,3,rep,name=shippingRegions,enum=CountryCode" json:"shippingRegions,omitempty"`
	EstimatedDelivery *Listing_Shipping_EstimatedDelivery `protobuf:"bytes,4,opt,name=estimatedDelivery" json:"estimatedDelivery,omitempty"`
	ShippingOrigin    CountryCode                         `protobuf:"varint,5,opt,name=shippingOrigin,enum=CountryCode" json:"shippingOrigin,omitempty"`
}

func (m *Listing_Shipping) Reset()                    { *m = Listing_Shipping{} }
func (m *Listing_Shipping) String() string            { return proto.CompactTextString(m) }
func (*Listing_Shipping) ProtoMessage()               {}
func (*Listing_Shipping) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1, 2} }

func (m *Listing_Shipping) GetDomestic() *Listing_Price {
	if m != nil {
		return m.Domestic
	}
	return nil
}

func (m *Listing_Shipping) GetInternational() *Listing_Price {
	if m != nil {
		return m.International
	}
	return nil
}

func (m *Listing_Shipping) GetEstimatedDelivery() *Listing_Shipping_EstimatedDelivery {
	if m != nil {
		return m.EstimatedDelivery
	}
	return nil
}

type Listing_Shipping_EstimatedDelivery struct {
	Domestic      string `protobuf:"bytes,1,opt,name=domestic" json:"domestic,omitempty"`
	International string `protobuf:"bytes,2,opt,name=international" json:"international,omitempty"`
}

func (m *Listing_Shipping_EstimatedDelivery) Reset()         { *m = Listing_Shipping_EstimatedDelivery{} }
func (m *Listing_Shipping_EstimatedDelivery) String() string { return proto.CompactTextString(m) }
func (*Listing_Shipping_EstimatedDelivery) ProtoMessage()    {}
func (*Listing_Shipping_EstimatedDelivery) Descriptor() ([]byte, []int) {
	return fileDescriptor1, []int{1, 2, 0}
}

type Listing_Price struct {
	Bitcoin uint32              `protobuf:"varint,1,opt,name=bitcoin" json:"bitcoin,omitempty"`
	Fiat    *Listing_Price_Fiat `protobuf:"bytes,2,opt,name=fiat" json:"fiat,omitempty"`
}

func (m *Listing_Price) Reset()                    { *m = Listing_Price{} }
func (m *Listing_Price) String() string            { return proto.CompactTextString(m) }
func (*Listing_Price) ProtoMessage()               {}
func (*Listing_Price) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1, 3} }

func (m *Listing_Price) GetFiat() *Listing_Price_Fiat {
	if m != nil {
		return m.Fiat
	}
	return nil
}

type Listing_Price_Fiat struct {
	CurrencyCode string  `protobuf:"bytes,1,opt,name=currencyCode" json:"currencyCode,omitempty"`
	Price        float32 `protobuf:"fixed32,2,opt,name=price" json:"price,omitempty"`
}

func (m *Listing_Price_Fiat) Reset()                    { *m = Listing_Price_Fiat{} }
func (m *Listing_Price_Fiat) String() string            { return proto.CompactTextString(m) }
func (*Listing_Price_Fiat) ProtoMessage()               {}
func (*Listing_Price_Fiat) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1, 3, 0} }

type Order struct {
	RefundAddress string          `protobuf:"bytes,1,opt,name=refundAddress" json:"refundAddress,omitempty"`
	Shipping      *Order_Shipping `protobuf:"bytes,2,opt,name=shipping" json:"shipping,omitempty"`
	BuyerID       *ID             `protobuf:"bytes,3,opt,name=buyerID" json:"buyerID,omitempty"`
	Timestamp     uint64          `protobuf:"varint,4,opt,name=timestamp" json:"timestamp,omitempty"`
	Items         []*Order_Item   `protobuf:"bytes,5,rep,name=items" json:"items,omitempty"`
	Payment       *Order_Payment  `protobuf:"bytes,6,opt,name=payment" json:"payment,omitempty"`
}

func (m *Order) Reset()                    { *m = Order{} }
func (m *Order) String() string            { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()               {}
func (*Order) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *Order) GetShipping() *Order_Shipping {
	if m != nil {
		return m.Shipping
	}
	return nil
}

func (m *Order) GetBuyerID() *ID {
	if m != nil {
		return m.BuyerID
	}
	return nil
}

func (m *Order) GetItems() []*Order_Item {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *Order) GetPayment() *Order_Payment {
	if m != nil {
		return m.Payment
	}
	return nil
}

type Order_Shipping struct {
	ShipTo     string                   `protobuf:"bytes,1,opt,name=shipTo" json:"shipTo,omitempty"`
	Address    string                   `protobuf:"bytes,2,opt,name=address" json:"address,omitempty"`
	City       string                   `protobuf:"bytes,3,opt,name=city" json:"city,omitempty"`
	State      string                   `protobuf:"bytes,4,opt,name=state" json:"state,omitempty"`
	PostalCode string                   `protobuf:"bytes,5,opt,name=postalCode" json:"postalCode,omitempty"`
	Country    CountryCode              `protobuf:"varint,6,opt,name=country,enum=CountryCode" json:"country,omitempty"`
}

func (m *Order_Shipping) Reset()                    { *m = Order_Shipping{} }
func (m *Order_Shipping) String() string            { return proto.CompactTextString(m) }
func (*Order_Shipping) ProtoMessage()               {}
func (*Order_Shipping) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2, 0} }

type Order_Item struct {
	ListingHash []byte               `protobuf:"bytes,1,opt,name=listingHash,proto3" json:"listingHash,omitempty"`
	Quantity    uint32               `protobuf:"varint,2,opt,name=quantity" json:"quantity,omitempty"`
	Options     []*Order_Item_Option `protobuf:"bytes,3,rep,name=options" json:"options,omitempty"`
}

func (m *Order_Item) Reset()                    { *m = Order_Item{} }
func (m *Order_Item) String() string            { return proto.CompactTextString(m) }
func (*Order_Item) ProtoMessage()               {}
func (*Order_Item) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2, 1} }

func (m *Order_Item) GetOptions() []*Order_Item_Option {
	if m != nil {
		return m.Options
	}
	return nil
}

type Order_Item_Option struct {
	Name  string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
}

func (m *Order_Item_Option) Reset()                    { *m = Order_Item_Option{} }
func (m *Order_Item_Option) String() string            { return proto.CompactTextString(m) }
func (*Order_Item_Option) ProtoMessage()               {}
func (*Order_Item_Option) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2, 1, 0} }

type Order_Payment struct {
	Method       Order_Payment_Method `protobuf:"varint,1,opt,name=method,enum=Order_Payment_Method" json:"method,omitempty"`
	Moderator    string               `protobuf:"bytes,2,opt,name=moderator" json:"moderator,omitempty"`
	Amount       uint32               `protobuf:"varint,3,opt,name=amount" json:"amount,omitempty"`
	Chaincode    string               `protobuf:"bytes,4,opt,name=chaincode" json:"chaincode,omitempty"`
	Address      string               `protobuf:"bytes,5,opt,name=address" json:"address,omitempty"`
	RedeemScript string               `protobuf:"bytes,6,opt,name=redeemScript" json:"redeemScript,omitempty"`
}

func (m *Order_Payment) Reset()                    { *m = Order_Payment{} }
func (m *Order_Payment) String() string            { return proto.CompactTextString(m) }
func (*Order_Payment) ProtoMessage()               {}
func (*Order_Payment) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2, 2} }

// TODO: complete other messages
type OrderConfirmation struct {
}

func (m *OrderConfirmation) Reset()                    { *m = OrderConfirmation{} }
func (m *OrderConfirmation) String() string            { return proto.CompactTextString(m) }
func (*OrderConfirmation) ProtoMessage()               {}
func (*OrderConfirmation) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

type Rating struct {
}

func (m *Rating) Reset()                    { *m = Rating{} }
func (m *Rating) String() string            { return proto.CompactTextString(m) }
func (*Rating) ProtoMessage()               {}
func (*Rating) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

type Dispute struct {
}

func (m *Dispute) Reset()                    { *m = Dispute{} }
func (m *Dispute) String() string            { return proto.CompactTextString(m) }
func (*Dispute) ProtoMessage()               {}
func (*Dispute) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{5} }

type DisputeResolution struct {
}

func (m *DisputeResolution) Reset()                    { *m = DisputeResolution{} }
func (m *DisputeResolution) String() string            { return proto.CompactTextString(m) }
func (*DisputeResolution) ProtoMessage()               {}
func (*DisputeResolution) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{6} }

type Refund struct {
}

func (m *Refund) Reset()                    { *m = Refund{} }
func (m *Refund) String() string            { return proto.CompactTextString(m) }
func (*Refund) ProtoMessage()               {}
func (*Refund) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{7} }

type ID struct {
	Guid         string      `protobuf:"bytes,1,opt,name=guid" json:"guid,omitempty"`
	BlockchainID string      `protobuf:"bytes,2,opt,name=blockchainID" json:"blockchainID,omitempty"`
	Pubkeys      *ID_Pubkeys `protobuf:"bytes,3,opt,name=pubkeys" json:"pubkeys,omitempty"`
}

func (m *ID) Reset()                    { *m = ID{} }
func (m *ID) String() string            { return proto.CompactTextString(m) }
func (*ID) ProtoMessage()               {}
func (*ID) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{8} }

func (m *ID) GetPubkeys() *ID_Pubkeys {
	if m != nil {
		return m.Pubkeys
	}
	return nil
}

type ID_Pubkeys struct {
	Guid    []byte `protobuf:"bytes,1,opt,name=guid,proto3" json:"guid,omitempty"`
	Bitcoin []byte `protobuf:"bytes,2,opt,name=bitcoin,proto3" json:"bitcoin,omitempty"`
}

func (m *ID_Pubkeys) Reset()                    { *m = ID_Pubkeys{} }
func (m *ID_Pubkeys) String() string            { return proto.CompactTextString(m) }
func (*ID_Pubkeys) ProtoMessage()               {}
func (*ID_Pubkeys) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{8, 0} }

type Signatures struct {
	Section Signatures_Section `protobuf:"varint,1,opt,name=section,enum=Signatures_Section" json:"section,omitempty"`
	Guid    []byte             `protobuf:"bytes,2,opt,name=guid,proto3" json:"guid,omitempty"`
	Bitcoin []byte             `protobuf:"bytes,3,opt,name=bitcoin,proto3" json:"bitcoin,omitempty"`
}

func (m *Signatures) Reset()                    { *m = Signatures{} }
func (m *Signatures) String() string            { return proto.CompactTextString(m) }
func (*Signatures) ProtoMessage()               {}
func (*Signatures) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{9} }

func init() {
	proto.RegisterType((*RicardianContract)(nil), "RicardianContract")
	proto.RegisterType((*Listing)(nil), "Listing")
	proto.RegisterType((*Listing_Metadata)(nil), "Listing.Metadata")
	proto.RegisterType((*Listing_Item)(nil), "Listing.Item")
	proto.RegisterType((*Listing_Item_Option)(nil), "Listing.Item.Option")
	proto.RegisterType((*Listing_Shipping)(nil), "Listing.Shipping")
	proto.RegisterType((*Listing_Shipping_EstimatedDelivery)(nil), "Listing.Shipping.EstimatedDelivery")
	proto.RegisterType((*Listing_Price)(nil), "Listing.Price")
	proto.RegisterType((*Listing_Price_Fiat)(nil), "Listing.Price.Fiat")
	proto.RegisterType((*Order)(nil), "Order")
	proto.RegisterType((*Order_Shipping)(nil), "Order.Shipping")
	proto.RegisterType((*Order_Item)(nil), "Order.Item")
	proto.RegisterType((*Order_Item_Option)(nil), "Order.Item.Option")
	proto.RegisterType((*Order_Payment)(nil), "Order.Payment")
	proto.RegisterType((*OrderConfirmation)(nil), "OrderConfirmation")
	proto.RegisterType((*Rating)(nil), "Rating")
	proto.RegisterType((*Dispute)(nil), "Dispute")
	proto.RegisterType((*DisputeResolution)(nil), "DisputeResolution")
	proto.RegisterType((*Refund)(nil), "Refund")
	proto.RegisterType((*ID)(nil), "ID")
	proto.RegisterType((*ID_Pubkeys)(nil), "ID.Pubkeys")
	proto.RegisterType((*Signatures)(nil), "Signatures")
	proto.RegisterEnum("Listing_Metadata_CategorySub", Listing_Metadata_CategorySub_name, Listing_Metadata_CategorySub_value)
	proto.RegisterEnum("Listing_Metadata_Category", Listing_Metadata_Category_name, Listing_Metadata_Category_value)
	proto.RegisterEnum("Order_Payment_Method", Order_Payment_Method_name, Order_Payment_Method_value)
	proto.RegisterEnum("Signatures_Section", Signatures_Section_name, Signatures_Section_value)
}

var fileDescriptor1 = []byte{
	// 1462 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x57, 0x4b, 0x93, 0xda, 0xc6,
	0x16, 0xbe, 0x20, 0x9e, 0x87, 0x19, 0x66, 0xa6, 0xed, 0xeb, 0x4b, 0x51, 0xd7, 0xf7, 0x3a, 0x38,
	0x0f, 0xe7, 0xa5, 0x4a, 0x8d, 0x53, 0xc9, 0x32, 0xa6, 0x80, 0xb1, 0x55, 0x1e, 0x03, 0x69, 0xc0,
	0x49, 0x56, 0x53, 0x1a, 0xa9, 0x87, 0xe9, 0x32, 0x48, 0x44, 0x12, 0x93, 0xb0, 0xcf, 0x32, 0xbf,
	0x20, 0xe5, 0x75, 0x96, 0xae, 0x6c, 0xf2, 0x83, 0xf2, 0x0b, 0xf2, 0x17, 0x72, 0xfa, 0x74, 0x0b,
	0x04, 0x8c, 0x53, 0xd9, 0xf5, 0x79, 0xa9, 0x4f, 0x7f, 0xe7, 0x29, 0x38, 0xf2, 0xc2, 0x20, 0x89,
	0x5c, 0x2f, 0x89, 0xed, 0x45, 0x14, 0x26, 0x61, 0x93, 0x79, 0xe1, 0x12, 0x39, 0x2b, 0x2f, 0xf4,
	0x85, 0xe1, 0xb5, 0x7e, 0xb1, 0xe0, 0x84, 0x4b, 0xcf, 0x8d, 0x7c, 0xe9, 0x06, 0x1d, 0x63, 0xc0,
	0x3e, 0x83, 0xfa, 0x8d, 0x08, 0xfc, 0x30, 0x3a, 0x97, 0x71, 0x22, 0x83, 0x69, 0xdc, 0xc8, 0x3d,
	0xb0, 0x1e, 0xd5, 0x4e, 0x2b, 0xb6, 0x61, 0xf0, 0x1d, 0x39, 0x7b, 0x1f, 0xe0, 0x72, 0xb9, 0x12,
	0xd1, 0x20, 0xf2, 0x45, 0xd4, 0xc8, 0x3f, 0xc8, 0xa1, 0x76, 0xc9, 0x26, 0x8a, 0x67, 0x24, 0xec,
	0x1c, 0xfe, 0xa3, 0x2d, 0x89, 0xc4, 0x0b, 0xaf, 0x64, 0x34, 0x77, 0x13, 0x19, 0x06, 0x0d, 0x8b,
	0x8c, 0x98, 0xbd, 0x27, 0xe1, 0x6f, 0x33, 0x61, 0x1f, 0x42, 0x8d, 0xbe, 0xcd, 0x5d, 0xe5, 0x45,
	0xa3, 0x40, 0x5f, 0x28, 0xdb, 0x9a, 0xe4, 0x59, 0x19, 0x6b, 0x41, 0xd9, 0x97, 0xf1, 0x62, 0x99,
	0x88, 0x46, 0x91, 0xd4, 0x2a, 0x76, 0x57, 0xd3, 0x3c, 0x15, 0xb0, 0x27, 0x70, 0x62, 0x8e, 0x5c,
	0xc4, 0xe1, 0x6c, 0x49, 0x6e, 0x95, 0x8c, 0x5b, 0xdd, 0x5d, 0x09, 0xdf, 0x57, 0x66, 0xff, 0x87,
	0x52, 0x24, 0xae, 0x96, 0x81, 0xdf, 0x28, 0xa7, 0xbe, 0x10, 0xc9, 0x0d, 0x9b, 0x7d, 0x0c, 0x10,
	0xcb, 0x69, 0xe0, 0x26, 0xcb, 0x48, 0xc4, 0x8d, 0x0a, 0xa1, 0x5a, 0xb3, 0x47, 0x6b, 0x16, 0xcf,
	0x88, 0x5b, 0x6f, 0x0e, 0xa0, 0x6c, 0x10, 0x66, 0x0f, 0xa0, 0x36, 0xd3, 0xc7, 0xbe, 0x3b, 0x17,
	0x18, 0x8f, 0xdc, 0xa3, 0x2a, 0xcf, 0xb2, 0xf0, 0xee, 0x8a, 0xc6, 0xc9, 0xe9, 0x9a, 0x00, 0x58,
	0xb6, 0xd3, 0xe5, 0x6b, 0x26, 0xfb, 0x14, 0x2a, 0x73, 0x91, 0xb8, 0xbe, 0x9b, 0xb8, 0x06, 0xec,
	0x93, 0x34, 0x9e, 0xf6, 0x0b, 0x23, 0xe0, 0x6b, 0x15, 0xf6, 0x0e, 0x14, 0x64, 0x22, 0xe6, 0x06,
	0xd5, 0xc3, 0xb5, 0xaa, 0x83, 0x4c, 0x4e, 0x22, 0xf5, 0xc5, 0xf8, 0x5a, 0x2e, 0x16, 0x0a, 0xfc,
	0xe2, 0xce, 0x17, 0x47, 0x46, 0xc0, 0xd7, 0x2a, 0xec, 0x7f, 0x00, 0x73, 0xcc, 0xbd, 0xc8, 0x4d,
	0xc2, 0x28, 0x46, 0x60, 0x2d, 0x7c, 0x42, 0x86, 0xc3, 0x6c, 0x60, 0x89, 0x88, 0xe6, 0x71, 0x3b,
	0xf0, 0x31, 0xcc, 0xbe, 0x54, 0x90, 0xc6, 0x84, 0x64, 0x95, 0xdf, 0x22, 0xc1, 0x98, 0x1e, 0x68,
	0x58, 0x87, 0xe1, 0x4c, 0x7a, 0x2b, 0x84, 0x53, 0x69, 0x6e, 0xf1, 0x9a, 0xbf, 0xe7, 0xa1, 0x92,
	0x3e, 0x8e, 0x35, 0xa0, 0x7c, 0x23, 0xa2, 0x58, 0x85, 0x55, 0x01, 0x78, 0xc8, 0x53, 0x92, 0x7d,
	0x01, 0x15, 0xcf, 0x4d, 0xc4, 0x34, 0x8c, 0x56, 0x04, 0x5e, 0xfd, 0xb4, 0xb9, 0x87, 0x8d, 0xdd,
	0x31, 0x1a, 0x7c, 0xad, 0xcb, 0xbe, 0x82, 0x5a, 0x7a, 0x1e, 0x2d, 0x2f, 0x09, 0xd6, 0xfa, 0xe9,
	0xfd, 0xb7, 0x9b, 0xa2, 0x12, 0xcf, 0x5a, 0xb0, 0x7b, 0x50, 0x12, 0x3f, 0x2e, 0x24, 0x5e, 0xab,
	0x70, 0x2e, 0x70, 0x43, 0xb5, 0x1e, 0x43, 0x2d, 0x63, 0xc3, 0x4a, 0x90, 0xef, 0xb7, 0x8f, 0xff,
	0xc5, 0x8e, 0xa0, 0x76, 0xe6, 0x7c, 0xdb, 0xeb, 0x5e, 0x0c, 0xb9, 0xd3, 0xe9, 0x1d, 0xe7, 0x58,
	0x0d, 0xca, 0xed, 0x49, 0x67, 0xec, 0x0c, 0xfa, 0xc7, 0xf9, 0x96, 0x03, 0x95, 0xd4, 0x48, 0x09,
	0x26, 0xfd, 0xe7, 0xfd, 0xc1, 0x37, 0x7d, 0x34, 0x3b, 0x81, 0xc3, 0xe1, 0xb3, 0xef, 0x46, 0x4e,
	0xa7, 0x7d, 0x7e, 0xf1, 0x74, 0x30, 0xe8, 0xa2, 0xe1, 0x31, 0x1c, 0x74, 0x9d, 0xa7, 0xce, 0x38,
	0xe5, 0xe4, 0x95, 0xc5, 0xa8, 0xc7, 0x5f, 0xaa, 0xef, 0x5a, 0xcd, 0xd7, 0x16, 0x14, 0x54, 0xa4,
	0xd9, 0x5d, 0x28, 0x26, 0x32, 0x99, 0xa5, 0x29, 0xa7, 0x09, 0x95, 0x8e, 0xd8, 0x44, 0xbc, 0x48,
	0x2e, 0xa8, 0x48, 0xf2, 0x3a, 0x1d, 0x33, 0x2c, 0xec, 0x08, 0x75, 0x6c, 0x31, 0x9e, 0x88, 0x63,
	0x04, 0x62, 0x2c, 0x31, 0x67, 0x2d, 0x52, 0xda, 0xe1, 0xb2, 0x53, 0x38, 0x58, 0x44, 0xd2, 0x13,
	0x43, 0x11, 0x4d, 0x02, 0x99, 0x98, 0x74, 0xab, 0xaf, 0x21, 0x1c, 0x2a, 0x21, 0xdf, 0xd2, 0x61,
	0x0c, 0x0a, 0x41, 0x7c, 0xf5, 0x03, 0xe5, 0x5c, 0x85, 0xd3, 0x59, 0xf1, 0x12, 0x77, 0x9a, 0xa6,
	0x15, 0x9d, 0x95, 0x97, 0x72, 0xee, 0x4e, 0xc5, 0x33, 0x37, 0xbe, 0x16, 0x2a, 0x93, 0x94, 0x28,
	0xcb, 0x42, 0x14, 0xac, 0xd1, 0xf3, 0x89, 0xc9, 0x1c, 0x2b, 0x7e, 0x3e, 0x61, 0xff, 0x85, 0xaa,
	0x97, 0xa6, 0x58, 0xa3, 0x4a, 0xfc, 0x0d, 0x03, 0x53, 0xb4, 0x1c, 0x2e, 0x74, 0x5e, 0x02, 0x15,
	0xef, 0xdd, 0xad, 0xba, 0xb0, 0x07, 0x24, 0xe4, 0xa9, 0x52, 0xf3, 0x25, 0x94, 0x34, 0x8b, 0x7c,
	0xde, 0x54, 0x2e, 0x9d, 0xff, 0x01, 0x8a, 0x98, 0x1e, 0x37, 0xee, 0x6c, 0x89, 0xce, 0x5b, 0xe4,
	0xbc, 0xa1, 0x9a, 0x3f, 0x59, 0x50, 0x49, 0x2b, 0x8c, 0x7d, 0x04, 0x15, 0x3f, 0x9c, 0x0b, 0x74,
	0xc3, 0xa3, 0xcf, 0xef, 0xc3, 0xb7, 0x96, 0xb3, 0xcf, 0xe1, 0x50, 0x06, 0x58, 0x4b, 0x01, 0x75,
	0x50, 0x77, 0x66, 0x5a, 0xc5, 0xae, 0xc1, 0xb6, 0x12, 0x96, 0xc7, 0x51, 0x5a, 0xc5, 0x5c, 0x4c,
	0xe9, 0xf9, 0xca, 0x9f, 0xfa, 0xe9, 0x81, 0xdd, 0xd1, 0x43, 0xa5, 0x83, 0x65, 0xcc, 0x77, 0x95,
	0xd8, 0xd7, 0x70, 0xa2, 0xae, 0xc5, 0x76, 0x2d, 0xfc, 0xae, 0x98, 0x49, 0x2c, 0xb7, 0x95, 0x89,
	0xf0, 0xc3, 0xbd, 0x4e, 0x61, 0xf7, 0x76, 0x55, 0xf9, 0xbe, 0x35, 0x3e, 0xa0, 0x9e, 0xde, 0x32,
	0x88, 0xe4, 0x54, 0x06, 0x94, 0x05, 0xbb, 0x9e, 0xec, 0xe8, 0x34, 0x27, 0x70, 0xb2, 0xf7, 0x75,
	0xd6, 0xdc, 0xc1, 0xad, 0x9a, 0xc1, 0xe9, 0xdd, 0xdb, 0x70, 0xaa, 0xee, 0xe0, 0xd2, 0xfc, 0x39,
	0x07, 0x45, 0x02, 0x4c, 0xb5, 0x96, 0x4b, 0x99, 0x78, 0xa1, 0x5c, 0xb7, 0x16, 0x43, 0xb2, 0x0f,
	0xa0, 0x70, 0x25, 0xdd, 0xc4, 0x00, 0x7d, 0x67, 0x1b, 0x68, 0xfb, 0x0c, 0x45, 0x9c, 0x14, 0x9a,
	0x4f, 0xa0, 0xa0, 0x28, 0xd5, 0xd6, 0xbc, 0x65, 0x14, 0x89, 0xc0, 0xa3, 0xb7, 0x18, 0xd7, 0xb6,
	0x78, 0xaa, 0x2a, 0xa9, 0x22, 0xe8, 0xab, 0x79, 0xae, 0x89, 0xd6, 0x6f, 0x25, 0x28, 0xea, 0x39,
	0x8b, 0xee, 0xeb, 0x36, 0xd8, 0xf6, 0x7d, 0x1c, 0x25, 0xb1, 0xf9, 0xc8, 0x36, 0x13, 0xa7, 0xd1,
	0xa6, 0x7f, 0x6b, 0xf7, 0x8e, 0xf4, 0xf8, 0xbd, 0xad, 0x7b, 0xdf, 0xc7, 0x17, 0xaa, 0x81, 0x8a,
	0xe3, 0xc5, 0xda, 0x8c, 0x97, 0x94, 0xa7, 0xea, 0x06, 0xf1, 0x45, 0xf0, 0xdc, 0xf9, 0xc2, 0xf4,
	0xb2, 0x0d, 0x03, 0x87, 0x49, 0x51, 0x4d, 0x8c, 0x18, 0x83, 0xa5, 0x47, 0x9e, 0xbe, 0x86, 0x66,
	0x89, 0x96, 0xb0, 0x47, 0x50, 0x5e, 0xb8, 0xab, 0xb9, 0x08, 0x12, 0x33, 0x73, 0xeb, 0x46, 0x69,
	0xa8, 0xb9, 0x3c, 0x15, 0x37, 0xdf, 0xe4, 0x32, 0xc9, 0x8f, 0x15, 0xa2, 0x5c, 0x1c, 0x87, 0xe6,
	0x89, 0x86, 0x52, 0x01, 0x71, 0xcd, 0xdb, 0x75, 0xe8, 0x52, 0x52, 0x55, 0xa2, 0x27, 0x93, 0x95,
	0xe9, 0x47, 0x74, 0x56, 0x78, 0xa2, 0xa3, 0xb8, 0x1c, 0x14, 0x74, 0x97, 0x23, 0x42, 0x0d, 0xac,
	0x45, 0x88, 0xc7, 0x19, 0xc5, 0xa1, 0x48, 0xa2, 0x0c, 0x07, 0x7b, 0x5c, 0xd9, 0xec, 0x54, 0xe4,
	0xf2, 0x6e, 0x12, 0xa6, 0xc2, 0xe6, 0xaf, 0x39, 0xd3, 0x4c, 0x37, 0x53, 0x5c, 0xf5, 0x1f, 0xf2,
	0xf8, 0x80, 0x67, 0x59, 0x2a, 0x27, 0xbf, 0x5f, 0xba, 0x41, 0xa2, 0x1c, 0xcc, 0x53, 0x22, 0xad,
	0x69, 0xf6, 0xc9, 0xa6, 0xf9, 0x58, 0x04, 0x23, 0xcb, 0xc0, 0xb8, 0xd7, 0x7a, 0x4e, 0xff, 0xb6,
	0xf5, 0xe0, 0x83, 0xa9, 0x95, 0x18, 0x70, 0x34, 0xd1, 0xfc, 0x33, 0x07, 0x65, 0x03, 0x37, 0x0e,
	0xf7, 0x12, 0xee, 0x02, 0xd7, 0xa1, 0x4f, 0x76, 0xf5, 0xd3, 0x7f, 0x6f, 0x87, 0x43, 0xcd, 0x36,
	0x14, 0x72, 0xa3, 0xa4, 0xe2, 0xbf, 0x1e, 0xe5, 0xe6, 0xa3, 0x1b, 0x86, 0x8a, 0x92, 0x3b, 0x57,
	0x68, 0x10, 0xea, 0x87, 0xdc, 0x50, 0xd4, 0x6d, 0xaf, 0x5d, 0x19, 0xa8, 0x9d, 0xd4, 0x60, 0xbf,
	0x61, 0x64, 0x63, 0x58, 0xdc, 0x8e, 0x21, 0x8d, 0x7e, 0x5f, 0x88, 0xf9, 0x88, 0x5a, 0x25, 0xc1,
	0x4f, 0xa3, 0x7f, 0xc3, 0x6b, 0x3d, 0x84, 0x92, 0xf6, 0x91, 0x01, 0x94, 0xba, 0x0e, 0xef, 0x75,
	0xc6, 0x38, 0x0a, 0x0f, 0xa1, 0xfa, 0x62, 0xd0, 0xed, 0xf1, 0xf6, 0xb8, 0x87, 0x63, 0xb0, 0x75,
	0x07, 0x4e, 0xf6, 0xf6, 0xca, 0x56, 0x05, 0x4a, 0x7a, 0x6d, 0x6c, 0x55, 0xa1, 0x6c, 0x16, 0x3f,
	0xa5, 0xb9, 0xb7, 0x03, 0x92, 0x26, 0x95, 0x54, 0xeb, 0x75, 0x0e, 0xf2, 0x58, 0x06, 0x88, 0xf5,
	0x74, 0x29, 0xfd, 0x14, 0x6b, 0x75, 0x56, 0xce, 0x5e, 0xce, 0x42, 0xef, 0x15, 0x3d, 0xcc, 0x6c,
	0x67, 0xe8, 0x6c, 0x96, 0xc7, 0xde, 0xc3, 0xec, 0x5f, 0x5e, 0xbe, 0x12, 0xab, 0xd8, 0x54, 0x57,
	0x0d, 0xab, 0xcb, 0x1e, 0x6a, 0x16, 0x4f, 0x65, 0xcd, 0x2f, 0x31, 0x3e, 0xfa, 0xb8, 0x75, 0xd3,
	0x81, 0xb9, 0x29, 0xd3, 0x85, 0xf2, 0xc4, 0x4e, 0xc9, 0xd6, 0x1f, 0x39, 0x80, 0xcd, 0x9a, 0x89,
	0xc1, 0x2d, 0xc7, 0xc2, 0x4b, 0xd2, 0x4d, 0xa8, 0x8e, 0x7d, 0x69, 0x23, 0xb5, 0x47, 0x5a, 0xc4,
	0x53, 0x9d, 0xf5, 0x5d, 0xf9, 0xdb, 0xef, 0xb2, 0xb6, 0xef, 0xba, 0xc1, 0x45, 0xc2, 0x18, 0xe2,
	0x4e, 0x71, 0xee, 0x8c, 0xc6, 0x4e, 0xff, 0x29, 0x42, 0x5f, 0xc5, 0xee, 0xc4, 0x11, 0x7a, 0xdc,
	0x3e, 0xee, 0x01, 0xa3, 0xe3, 0x45, 0x67, 0xd0, 0x3f, 0x73, 0xf8, 0x8b, 0xb6, 0xde, 0x60, 0x54,
	0xa4, 0x30, 0x32, 0x4a, 0xdd, 0x52, 0xb6, 0x5d, 0x67, 0x34, 0x9c, 0x8c, 0x7b, 0xc7, 0x05, 0x65,
	0x60, 0x88, 0x0b, 0xde, 0x1b, 0x0d, 0xce, 0x27, 0x64, 0x50, 0x24, 0x83, 0xde, 0xd9, 0xa4, 0xdf,
	0x3d, 0x2e, 0x5d, 0x96, 0xe8, 0x9f, 0xe6, 0xf1, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x9a, 0x68,
	0x1d, 0xe0, 0xfa, 0x0c, 0x00, 0x00,
}
