// Code generated by protoc-gen-go. DO NOT EDIT.
// source: countrycodes.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CountryCode int32

const (
	CountryCode_NA                             CountryCode = 0
	CountryCode_AFGHANISTAN                    CountryCode = 1
	CountryCode_ALAND_ISLANDS                  CountryCode = 2
	CountryCode_ALBANIA                        CountryCode = 3
	CountryCode_ALGERIA                        CountryCode = 4
	CountryCode_AMERICAN_SAMOA                 CountryCode = 5
	CountryCode_ANDORRA                        CountryCode = 6
	CountryCode_ANGOLA                         CountryCode = 7
	CountryCode_ANGUILLA                       CountryCode = 8
	CountryCode_ANTIGUA                        CountryCode = 9
	CountryCode_ARGENTINA                      CountryCode = 10
	CountryCode_ARMENIA                        CountryCode = 11
	CountryCode_ARUBA                          CountryCode = 12
	CountryCode_AUSTRALIA                      CountryCode = 13
	CountryCode_AUSTRIA                        CountryCode = 14
	CountryCode_AZERBAIJAN                     CountryCode = 15
	CountryCode_BAHAMAS                        CountryCode = 16
	CountryCode_BAHRAIN                        CountryCode = 17
	CountryCode_BANGLADESH                     CountryCode = 18
	CountryCode_BARBADOS                       CountryCode = 19
	CountryCode_BELARUS                        CountryCode = 20
	CountryCode_BELGIUM                        CountryCode = 21
	CountryCode_BELIZE                         CountryCode = 22
	CountryCode_BENIN                          CountryCode = 23
	CountryCode_BERMUDA                        CountryCode = 24
	CountryCode_BHUTAN                         CountryCode = 25
	CountryCode_BOLIVIA                        CountryCode = 26
	CountryCode_BONAIRE_SINT_EUSTATIUS_SABA    CountryCode = 27
	CountryCode_BOSNIA                         CountryCode = 28
	CountryCode_BOTSWANA                       CountryCode = 29
	CountryCode_BOUVET_ISLAND                  CountryCode = 30
	CountryCode_BRAZIL                         CountryCode = 31
	CountryCode_BRITISH_INDIAN_OCEAN_TERRITORY CountryCode = 32
	CountryCode_BRUNEI_DARUSSALAM              CountryCode = 33
	CountryCode_BULGARIA                       CountryCode = 34
	CountryCode_BURKINA_FASO                   CountryCode = 35
	CountryCode_BURUNDI                        CountryCode = 36
	CountryCode_CABO_VERDE                     CountryCode = 37
	CountryCode_CAMBODIA                       CountryCode = 38
	CountryCode_CAMEROON                       CountryCode = 39
	CountryCode_CANADA                         CountryCode = 40
	CountryCode_CAYMAN_ISLANDS                 CountryCode = 41
	CountryCode_CENTRAL_AFRICAN_REPUBLIC       CountryCode = 42
	CountryCode_CHAD                           CountryCode = 43
	CountryCode_CHILE                          CountryCode = 44
	CountryCode_CHINA                          CountryCode = 45
	CountryCode_CHRISTMAS_ISLAND               CountryCode = 46
	CountryCode_COCOS_ISLANDS                  CountryCode = 47
	CountryCode_COLOMBIA                       CountryCode = 48
	CountryCode_COMOROS                        CountryCode = 49
	CountryCode_CONGO_REPUBLIC                 CountryCode = 50
	CountryCode_CONGO                          CountryCode = 51
	CountryCode_COOK_ISLANDS                   CountryCode = 52
	CountryCode_COSTA_RICA                     CountryCode = 53
	CountryCode_COTE_DIVOIRE                   CountryCode = 54
	CountryCode_CROATIA                        CountryCode = 55
	CountryCode_CUBA                           CountryCode = 56
	CountryCode_CURACAO                        CountryCode = 57
	CountryCode_CYPRUS                         CountryCode = 58
	CountryCode_CZECH_REPUBLIC                 CountryCode = 59
	CountryCode_DENMARK                        CountryCode = 60
	CountryCode_DJIBOUTI                       CountryCode = 61
	CountryCode_DOMINICA                       CountryCode = 62
	CountryCode_DOMINICAN_REPUBLIC             CountryCode = 63
	CountryCode_ECUADOR                        CountryCode = 64
	CountryCode_EGYPT                          CountryCode = 65
	CountryCode_EL_SALVADOR                    CountryCode = 66
	CountryCode_EQUATORIAL_GUINEA              CountryCode = 67
	CountryCode_ERITREA                        CountryCode = 68
	CountryCode_ESTONIA                        CountryCode = 69
	CountryCode_ETHIOPIA                       CountryCode = 70
	CountryCode_FALKLAND_ISLANDS               CountryCode = 71
	CountryCode_FAROE_ISLANDS                  CountryCode = 72
	CountryCode_FIJI                           CountryCode = 73
	CountryCode_FINLAND                        CountryCode = 74
	CountryCode_FRANCE                         CountryCode = 75
	CountryCode_FRENCH_GUIANA                  CountryCode = 76
	CountryCode_FRENCH_POLYNESIA               CountryCode = 77
	CountryCode_FRENCH_SOUTHERN_TERRITORIES    CountryCode = 78
	CountryCode_GABON                          CountryCode = 79
	CountryCode_GAMBIA                         CountryCode = 80
	CountryCode_GEORGIA                        CountryCode = 81
	CountryCode_GERMANY                        CountryCode = 82
	CountryCode_GHANA                          CountryCode = 83
	CountryCode_GIBRALTAR                      CountryCode = 84
	CountryCode_GREECE                         CountryCode = 85
	CountryCode_GREENLAND                      CountryCode = 86
	CountryCode_GRENADA                        CountryCode = 87
	CountryCode_GUADELOUPE                     CountryCode = 88
	CountryCode_GUAM                           CountryCode = 89
	CountryCode_GUATEMALA                      CountryCode = 90
	CountryCode_GUERNSEY                       CountryCode = 91
	CountryCode_GUINEA                         CountryCode = 92
	CountryCode_GUINEA_BISSAU                  CountryCode = 93
	CountryCode_GUYANA                         CountryCode = 94
	CountryCode_HAITI                          CountryCode = 95
	CountryCode_HEARD_ISLAND                   CountryCode = 96
	CountryCode_HOLY_SEE                       CountryCode = 97
	CountryCode_HONDURAS                       CountryCode = 98
	CountryCode_HONG_KONG                      CountryCode = 99
	CountryCode_HUNGARY                        CountryCode = 100
	CountryCode_ICELAND                        CountryCode = 101
	CountryCode_INDIA                          CountryCode = 102
	CountryCode_INDONESIA                      CountryCode = 103
	CountryCode_IRAN                           CountryCode = 104
	CountryCode_IRAQ                           CountryCode = 105
	CountryCode_IRELAND                        CountryCode = 106
	CountryCode_ISLE_OF_MAN                    CountryCode = 107
	CountryCode_ISRAEL                         CountryCode = 108
	CountryCode_ITALY                          CountryCode = 109
	CountryCode_JAMAICA                        CountryCode = 110
	CountryCode_JAPAN                          CountryCode = 111
	CountryCode_JERSEY                         CountryCode = 112
	CountryCode_JORDAN                         CountryCode = 113
	CountryCode_KAZAKHSTAN                     CountryCode = 114
	CountryCode_KENYA                          CountryCode = 115
	CountryCode_KIRIBATI                       CountryCode = 116
	CountryCode_NORTH_KOREA                    CountryCode = 117
	CountryCode_SOUTH_KOREA                    CountryCode = 118
	CountryCode_KUWAIT                         CountryCode = 119
	CountryCode_KYRGYZSTAN                     CountryCode = 120
	CountryCode_LAO                            CountryCode = 121
	CountryCode_LATVIA                         CountryCode = 122
	CountryCode_LEBANON                        CountryCode = 123
	CountryCode_LESOTHO                        CountryCode = 124
	CountryCode_LIBERIA                        CountryCode = 125
	CountryCode_LIBYA                          CountryCode = 126
	CountryCode_LIECHTENSTEIN                  CountryCode = 127
	CountryCode_LITHUANIA                      CountryCode = 128
	CountryCode_LUXEMBOURG                     CountryCode = 129
	CountryCode_MACAO                          CountryCode = 130
	CountryCode_MACEDONIA                      CountryCode = 131
	CountryCode_MADAGASCAR                     CountryCode = 132
	CountryCode_MALAWI                         CountryCode = 133
	CountryCode_MALAYSIA                       CountryCode = 134
	CountryCode_MALDIVES                       CountryCode = 135
	CountryCode_MALI                           CountryCode = 136
	CountryCode_MALTA                          CountryCode = 137
	CountryCode_MARSHALL_ISLANDS               CountryCode = 138
	CountryCode_MARTINIQUE                     CountryCode = 139
	CountryCode_MAURITANIA                     CountryCode = 140
	CountryCode_MAURITIUS                      CountryCode = 141
	CountryCode_MAYOTTE                        CountryCode = 142
	CountryCode_MEXICO                         CountryCode = 143
	CountryCode_MICRONESIA                     CountryCode = 144
	CountryCode_MOLDOVA                        CountryCode = 145
	CountryCode_MONACO                         CountryCode = 146
	CountryCode_MONGOLIA                       CountryCode = 147
	CountryCode_MONTENEGRO                     CountryCode = 148
	CountryCode_MONTSERRAT                     CountryCode = 149
	CountryCode_MOROCCO                        CountryCode = 150
	CountryCode_MOZAMBIQUE                     CountryCode = 151
	CountryCode_MYANMAR                        CountryCode = 152
	CountryCode_NAMIBIA                        CountryCode = 153
	CountryCode_NAURU                          CountryCode = 154
	CountryCode_NEPAL                          CountryCode = 155
	CountryCode_NETHERLANDS                    CountryCode = 156
	CountryCode_NEW_CALEDONIA                  CountryCode = 157
	CountryCode_NEW_ZEALAND                    CountryCode = 158
	CountryCode_NICARAGUA                      CountryCode = 159
	CountryCode_NIGER                          CountryCode = 160
	CountryCode_NIGERIA                        CountryCode = 161
	CountryCode_NIUE                           CountryCode = 162
	CountryCode_NORFOLK_ISLAND                 CountryCode = 163
	CountryCode_NORTHERN_MARIANA_ISLANDS       CountryCode = 164
	CountryCode_NORWAY                         CountryCode = 165
	CountryCode_OMAN                           CountryCode = 166
	CountryCode_PAKISTAN                       CountryCode = 167
	CountryCode_PALAU                          CountryCode = 168
	CountryCode_PANAMA                         CountryCode = 169
	CountryCode_PAPUA_NEW_GUINEA               CountryCode = 170
	CountryCode_PARAGUAY                       CountryCode = 171
	CountryCode_PERU                           CountryCode = 172
	CountryCode_PHILIPPINES                    CountryCode = 173
	CountryCode_PITCAIRN                       CountryCode = 174
	CountryCode_POLAND                         CountryCode = 175
	CountryCode_PORTUGAL                       CountryCode = 176
	CountryCode_PUERTO_RICO                    CountryCode = 177
	CountryCode_QATAR                          CountryCode = 178
	CountryCode_REUNION                        CountryCode = 179
	CountryCode_ROMANIA                        CountryCode = 180
	CountryCode_RUSSIA                         CountryCode = 181
	CountryCode_RWANDA                         CountryCode = 182
	CountryCode_SAINT_BARTHELEMY               CountryCode = 183
	CountryCode_SAINT_HELENA                   CountryCode = 184
	CountryCode_SAINT_KITTS                    CountryCode = 185
	CountryCode_SAINT_LUCIA                    CountryCode = 186
	CountryCode_SAINT_MARTIN                   CountryCode = 187
	CountryCode_SAINT_PIERRE                   CountryCode = 188
	CountryCode_SAINT_VINCENT                  CountryCode = 189
	CountryCode_SAMOA                          CountryCode = 190
	CountryCode_SAN_MARINO                     CountryCode = 191
	CountryCode_SAO_TOME                       CountryCode = 192
	CountryCode_SAUDI_ARABIA                   CountryCode = 193
	CountryCode_SENEGAL                        CountryCode = 194
	CountryCode_SERBIA                         CountryCode = 195
	CountryCode_SEYCHELLES                     CountryCode = 196
	CountryCode_SIERRA_LEONE                   CountryCode = 197
	CountryCode_SINGAPORE                      CountryCode = 198
	CountryCode_SINT_MAARTEN                   CountryCode = 199
	CountryCode_SUCRE                          CountryCode = 200
	CountryCode_SLOVAKIA                       CountryCode = 201
	CountryCode_SLOVENIA                       CountryCode = 202
	CountryCode_SOLOMON_ISLANDS                CountryCode = 203
	CountryCode_SOMALIA                        CountryCode = 204
	CountryCode_SOUTH_AFRICA                   CountryCode = 205
	CountryCode_SOUTH_SUDAN                    CountryCode = 206
	CountryCode_SPAIN                          CountryCode = 207
	CountryCode_SRI_LANKA                      CountryCode = 208
	CountryCode_SUDAN                          CountryCode = 209
	CountryCode_SURINAME                       CountryCode = 210
	CountryCode_SVALBARD                       CountryCode = 211
	CountryCode_ESWATINI                       CountryCode = 212
	CountryCode_SWAZILAND                      CountryCode = 212
	CountryCode_SWEDEN                         CountryCode = 213
	CountryCode_SWITZERLAND                    CountryCode = 214
	CountryCode_SYRIAN_ARAB_REPUBLIC           CountryCode = 215
	CountryCode_TAIWAN                         CountryCode = 216
	CountryCode_TAJIKISTAN                     CountryCode = 217
	CountryCode_TANZANIA                       CountryCode = 218
	CountryCode_THAILAND                       CountryCode = 219
	CountryCode_TIMOR_LESTE                    CountryCode = 220
	CountryCode_TOGO                           CountryCode = 221
	CountryCode_TOKELAU                        CountryCode = 222
	CountryCode_TONGA                          CountryCode = 223
	CountryCode_TRINIDAD                       CountryCode = 224
	CountryCode_TUNISIA                        CountryCode = 225
	CountryCode_TURKEY                         CountryCode = 226
	CountryCode_TURKMENISTAN                   CountryCode = 227
	CountryCode_TURKS_AND_CAICOS_ISLANDS       CountryCode = 228
	CountryCode_TUVALU                         CountryCode = 229
	CountryCode_UGANDA                         CountryCode = 230
	CountryCode_UKRAINE                        CountryCode = 231
	CountryCode_UNITED_ARAB_EMIRATES           CountryCode = 232
	CountryCode_UNITED_KINGDOM                 CountryCode = 233
	CountryCode_UNITED_STATES                  CountryCode = 234
	CountryCode_URUGUAY                        CountryCode = 235
	CountryCode_UZBEKISTAN                     CountryCode = 236
	CountryCode_VANUATU                        CountryCode = 237
	CountryCode_VENEZUELA                      CountryCode = 238
	CountryCode_VIETNAM                        CountryCode = 239
	CountryCode_VIRGIN_ISLANDS_BRITISH         CountryCode = 240
	CountryCode_VIRGIN_ISLANDS_US              CountryCode = 241
	CountryCode_WALLIS_AND_FUTUNA              CountryCode = 242
	CountryCode_WESTERN_SAHARA                 CountryCode = 243
	CountryCode_YEMEN                          CountryCode = 244
	CountryCode_ZAMBIA                         CountryCode = 245
	CountryCode_ZIMBABWE                       CountryCode = 246
	CountryCode_UNITED_STATES_MINOR_ISLANDS    CountryCode = 247
	CountryCode_ALL                            CountryCode = 500
	CountryCode_AFRICA                         CountryCode = 501
	CountryCode_ASIA                           CountryCode = 502
	CountryCode_CENTRAL_AMERICA                CountryCode = 503
	CountryCode_EUROPE                         CountryCode = 504
	CountryCode_MIDDLE_EAST                    CountryCode = 505
	CountryCode_NORTH_AMERICA                  CountryCode = 506
	CountryCode_SOUTH_AMERICA                  CountryCode = 507
	CountryCode_OCEANIA                        CountryCode = 508
)

var CountryCode_name = map[int32]string{
	0:   "NA",
	1:   "AFGHANISTAN",
	2:   "ALAND_ISLANDS",
	3:   "ALBANIA",
	4:   "ALGERIA",
	5:   "AMERICAN_SAMOA",
	6:   "ANDORRA",
	7:   "ANGOLA",
	8:   "ANGUILLA",
	9:   "ANTIGUA",
	10:  "ARGENTINA",
	11:  "ARMENIA",
	12:  "ARUBA",
	13:  "AUSTRALIA",
	14:  "AUSTRIA",
	15:  "AZERBAIJAN",
	16:  "BAHAMAS",
	17:  "BAHRAIN",
	18:  "BANGLADESH",
	19:  "BARBADOS",
	20:  "BELARUS",
	21:  "BELGIUM",
	22:  "BELIZE",
	23:  "BENIN",
	24:  "BERMUDA",
	25:  "BHUTAN",
	26:  "BOLIVIA",
	27:  "BONAIRE_SINT_EUSTATIUS_SABA",
	28:  "BOSNIA",
	29:  "BOTSWANA",
	30:  "BOUVET_ISLAND",
	31:  "BRAZIL",
	32:  "BRITISH_INDIAN_OCEAN_TERRITORY",
	33:  "BRUNEI_DARUSSALAM",
	34:  "BULGARIA",
	35:  "BURKINA_FASO",
	36:  "BURUNDI",
	37:  "CABO_VERDE",
	38:  "CAMBODIA",
	39:  "CAMEROON",
	40:  "CANADA",
	41:  "CAYMAN_ISLANDS",
	42:  "CENTRAL_AFRICAN_REPUBLIC",
	43:  "CHAD",
	44:  "CHILE",
	45:  "CHINA",
	46:  "CHRISTMAS_ISLAND",
	47:  "COCOS_ISLANDS",
	48:  "COLOMBIA",
	49:  "COMOROS",
	50:  "CONGO_REPUBLIC",
	51:  "CONGO",
	52:  "COOK_ISLANDS",
	53:  "COSTA_RICA",
	54:  "COTE_DIVOIRE",
	55:  "CROATIA",
	56:  "CUBA",
	57:  "CURACAO",
	58:  "CYPRUS",
	59:  "CZECH_REPUBLIC",
	60:  "DENMARK",
	61:  "DJIBOUTI",
	62:  "DOMINICA",
	63:  "DOMINICAN_REPUBLIC",
	64:  "ECUADOR",
	65:  "EGYPT",
	66:  "EL_SALVADOR",
	67:  "EQUATORIAL_GUINEA",
	68:  "ERITREA",
	69:  "ESTONIA",
	70:  "ETHIOPIA",
	71:  "FALKLAND_ISLANDS",
	72:  "FAROE_ISLANDS",
	73:  "FIJI",
	74:  "FINLAND",
	75:  "FRANCE",
	76:  "FRENCH_GUIANA",
	77:  "FRENCH_POLYNESIA",
	78:  "FRENCH_SOUTHERN_TERRITORIES",
	79:  "GABON",
	80:  "GAMBIA",
	81:  "GEORGIA",
	82:  "GERMANY",
	83:  "GHANA",
	84:  "GIBRALTAR",
	85:  "GREECE",
	86:  "GREENLAND",
	87:  "GRENADA",
	88:  "GUADELOUPE",
	89:  "GUAM",
	90:  "GUATEMALA",
	91:  "GUERNSEY",
	92:  "GUINEA",
	93:  "GUINEA_BISSAU",
	94:  "GUYANA",
	95:  "HAITI",
	96:  "HEARD_ISLAND",
	97:  "HOLY_SEE",
	98:  "HONDURAS",
	99:  "HONG_KONG",
	100: "HUNGARY",
	101: "ICELAND",
	102: "INDIA",
	103: "INDONESIA",
	104: "IRAN",
	105: "IRAQ",
	106: "IRELAND",
	107: "ISLE_OF_MAN",
	108: "ISRAEL",
	109: "ITALY",
	110: "JAMAICA",
	111: "JAPAN",
	112: "JERSEY",
	113: "JORDAN",
	114: "KAZAKHSTAN",
	115: "KENYA",
	116: "KIRIBATI",
	117: "NORTH_KOREA",
	118: "SOUTH_KOREA",
	119: "KUWAIT",
	120: "KYRGYZSTAN",
	121: "LAO",
	122: "LATVIA",
	123: "LEBANON",
	124: "LESOTHO",
	125: "LIBERIA",
	126: "LIBYA",
	127: "LIECHTENSTEIN",
	128: "LITHUANIA",
	129: "LUXEMBOURG",
	130: "MACAO",
	131: "MACEDONIA",
	132: "MADAGASCAR",
	133: "MALAWI",
	134: "MALAYSIA",
	135: "MALDIVES",
	136: "MALI",
	137: "MALTA",
	138: "MARSHALL_ISLANDS",
	139: "MARTINIQUE",
	140: "MAURITANIA",
	141: "MAURITIUS",
	142: "MAYOTTE",
	143: "MEXICO",
	144: "MICRONESIA",
	145: "MOLDOVA",
	146: "MONACO",
	147: "MONGOLIA",
	148: "MONTENEGRO",
	149: "MONTSERRAT",
	150: "MOROCCO",
	151: "MOZAMBIQUE",
	152: "MYANMAR",
	153: "NAMIBIA",
	154: "NAURU",
	155: "NEPAL",
	156: "NETHERLANDS",
	157: "NEW_CALEDONIA",
	158: "NEW_ZEALAND",
	159: "NICARAGUA",
	160: "NIGER",
	161: "NIGERIA",
	162: "NIUE",
	163: "NORFOLK_ISLAND",
	164: "NORTHERN_MARIANA_ISLANDS",
	165: "NORWAY",
	166: "OMAN",
	167: "PAKISTAN",
	168: "PALAU",
	169: "PANAMA",
	170: "PAPUA_NEW_GUINEA",
	171: "PARAGUAY",
	172: "PERU",
	173: "PHILIPPINES",
	174: "PITCAIRN",
	175: "POLAND",
	176: "PORTUGAL",
	177: "PUERTO_RICO",
	178: "QATAR",
	179: "REUNION",
	180: "ROMANIA",
	181: "RUSSIA",
	182: "RWANDA",
	183: "SAINT_BARTHELEMY",
	184: "SAINT_HELENA",
	185: "SAINT_KITTS",
	186: "SAINT_LUCIA",
	187: "SAINT_MARTIN",
	188: "SAINT_PIERRE",
	189: "SAINT_VINCENT",
	190: "SAMOA",
	191: "SAN_MARINO",
	192: "SAO_TOME",
	193: "SAUDI_ARABIA",
	194: "SENEGAL",
	195: "SERBIA",
	196: "SEYCHELLES",
	197: "SIERRA_LEONE",
	198: "SINGAPORE",
	199: "SINT_MAARTEN",
	200: "SUCRE",
	201: "SLOVAKIA",
	202: "SLOVENIA",
	203: "SOLOMON_ISLANDS",
	204: "SOMALIA",
	205: "SOUTH_AFRICA",
	206: "SOUTH_SUDAN",
	207: "SPAIN",
	208: "SRI_LANKA",
	209: "SUDAN",
	210: "SURINAME",
	211: "SVALBARD",
	212: "ESWATINI",
	// Duplicate value: 212: "SWAZILAND",
	213: "SWEDEN",
	214: "SWITZERLAND",
	215: "SYRIAN_ARAB_REPUBLIC",
	216: "TAIWAN",
	217: "TAJIKISTAN",
	218: "TANZANIA",
	219: "THAILAND",
	220: "TIMOR_LESTE",
	221: "TOGO",
	222: "TOKELAU",
	223: "TONGA",
	224: "TRINIDAD",
	225: "TUNISIA",
	226: "TURKEY",
	227: "TURKMENISTAN",
	228: "TURKS_AND_CAICOS_ISLANDS",
	229: "TUVALU",
	230: "UGANDA",
	231: "UKRAINE",
	232: "UNITED_ARAB_EMIRATES",
	233: "UNITED_KINGDOM",
	234: "UNITED_STATES",
	235: "URUGUAY",
	236: "UZBEKISTAN",
	237: "VANUATU",
	238: "VENEZUELA",
	239: "VIETNAM",
	240: "VIRGIN_ISLANDS_BRITISH",
	241: "VIRGIN_ISLANDS_US",
	242: "WALLIS_AND_FUTUNA",
	243: "WESTERN_SAHARA",
	244: "YEMEN",
	245: "ZAMBIA",
	246: "ZIMBABWE",
	247: "UNITED_STATES_MINOR_ISLANDS",
	500: "ALL",
	501: "AFRICA",
	502: "ASIA",
	503: "CENTRAL_AMERICA",
	504: "EUROPE",
	505: "MIDDLE_EAST",
	506: "NORTH_AMERICA",
	507: "SOUTH_AMERICA",
	508: "OCEANIA",
}
var CountryCode_value = map[string]int32{
	"NA":                             0,
	"AFGHANISTAN":                    1,
	"ALAND_ISLANDS":                  2,
	"ALBANIA":                        3,
	"ALGERIA":                        4,
	"AMERICAN_SAMOA":                 5,
	"ANDORRA":                        6,
	"ANGOLA":                         7,
	"ANGUILLA":                       8,
	"ANTIGUA":                        9,
	"ARGENTINA":                      10,
	"ARMENIA":                        11,
	"ARUBA":                          12,
	"AUSTRALIA":                      13,
	"AUSTRIA":                        14,
	"AZERBAIJAN":                     15,
	"BAHAMAS":                        16,
	"BAHRAIN":                        17,
	"BANGLADESH":                     18,
	"BARBADOS":                       19,
	"BELARUS":                        20,
	"BELGIUM":                        21,
	"BELIZE":                         22,
	"BENIN":                          23,
	"BERMUDA":                        24,
	"BHUTAN":                         25,
	"BOLIVIA":                        26,
	"BONAIRE_SINT_EUSTATIUS_SABA":    27,
	"BOSNIA":                         28,
	"BOTSWANA":                       29,
	"BOUVET_ISLAND":                  30,
	"BRAZIL":                         31,
	"BRITISH_INDIAN_OCEAN_TERRITORY": 32,
	"BRUNEI_DARUSSALAM":              33,
	"BULGARIA":                       34,
	"BURKINA_FASO":                   35,
	"BURUNDI":                        36,
	"CABO_VERDE":                     37,
	"CAMBODIA":                       38,
	"CAMEROON":                       39,
	"CANADA":                         40,
	"CAYMAN_ISLANDS":                 41,
	"CENTRAL_AFRICAN_REPUBLIC":       42,
	"CHAD":                           43,
	"CHILE":                          44,
	"CHINA":                          45,
	"CHRISTMAS_ISLAND":               46,
	"COCOS_ISLANDS":                  47,
	"COLOMBIA":                       48,
	"COMOROS":                        49,
	"CONGO_REPUBLIC":                 50,
	"CONGO":                          51,
	"COOK_ISLANDS":                   52,
	"COSTA_RICA":                     53,
	"COTE_DIVOIRE":                   54,
	"CROATIA":                        55,
	"CUBA":                           56,
	"CURACAO":                        57,
	"CYPRUS":                         58,
	"CZECH_REPUBLIC":                 59,
	"DENMARK":                        60,
	"DJIBOUTI":                       61,
	"DOMINICA":                       62,
	"DOMINICAN_REPUBLIC":             63,
	"ECUADOR":                        64,
	"EGYPT":                          65,
	"EL_SALVADOR":                    66,
	"EQUATORIAL_GUINEA":              67,
	"ERITREA":                        68,
	"ESTONIA":                        69,
	"ETHIOPIA":                       70,
	"FALKLAND_ISLANDS":               71,
	"FAROE_ISLANDS":                  72,
	"FIJI":                           73,
	"FINLAND":                        74,
	"FRANCE":                         75,
	"FRENCH_GUIANA":                  76,
	"FRENCH_POLYNESIA":               77,
	"FRENCH_SOUTHERN_TERRITORIES":    78,
	"GABON":                          79,
	"GAMBIA":                         80,
	"GEORGIA":                        81,
	"GERMANY":                        82,
	"GHANA":                          83,
	"GIBRALTAR":                      84,
	"GREECE":                         85,
	"GREENLAND":                      86,
	"GRENADA":                        87,
	"GUADELOUPE":                     88,
	"GUAM":                           89,
	"GUATEMALA":                      90,
	"GUERNSEY":                       91,
	"GUINEA":                         92,
	"GUINEA_BISSAU":                  93,
	"GUYANA":                         94,
	"HAITI":                          95,
	"HEARD_ISLAND":                   96,
	"HOLY_SEE":                       97,
	"HONDURAS":                       98,
	"HONG_KONG":                      99,
	"HUNGARY":                        100,
	"ICELAND":                        101,
	"INDIA":                          102,
	"INDONESIA":                      103,
	"IRAN":                           104,
	"IRAQ":                           105,
	"IRELAND":                        106,
	"ISLE_OF_MAN":                    107,
	"ISRAEL":                         108,
	"ITALY":                          109,
	"JAMAICA":                        110,
	"JAPAN":                          111,
	"JERSEY":                         112,
	"JORDAN":                         113,
	"KAZAKHSTAN":                     114,
	"KENYA":                          115,
	"KIRIBATI":                       116,
	"NORTH_KOREA":                    117,
	"SOUTH_KOREA":                    118,
	"KUWAIT":                         119,
	"KYRGYZSTAN":                     120,
	"LAO":                            121,
	"LATVIA":                         122,
	"LEBANON":                        123,
	"LESOTHO":                        124,
	"LIBERIA":                        125,
	"LIBYA":                          126,
	"LIECHTENSTEIN":                  127,
	"LITHUANIA":                      128,
	"LUXEMBOURG":                     129,
	"MACAO":                          130,
	"MACEDONIA":                      131,
	"MADAGASCAR":                     132,
	"MALAWI":                         133,
	"MALAYSIA":                       134,
	"MALDIVES":                       135,
	"MALI":                           136,
	"MALTA":                          137,
	"MARSHALL_ISLANDS":               138,
	"MARTINIQUE":                     139,
	"MAURITANIA":                     140,
	"MAURITIUS":                      141,
	"MAYOTTE":                        142,
	"MEXICO":                         143,
	"MICRONESIA":                     144,
	"MOLDOVA":                        145,
	"MONACO":                         146,
	"MONGOLIA":                       147,
	"MONTENEGRO":                     148,
	"MONTSERRAT":                     149,
	"MOROCCO":                        150,
	"MOZAMBIQUE":                     151,
	"MYANMAR":                        152,
	"NAMIBIA":                        153,
	"NAURU":                          154,
	"NEPAL":                          155,
	"NETHERLANDS":                    156,
	"NEW_CALEDONIA":                  157,
	"NEW_ZEALAND":                    158,
	"NICARAGUA":                      159,
	"NIGER":                          160,
	"NIGERIA":                        161,
	"NIUE":                           162,
	"NORFOLK_ISLAND":                 163,
	"NORTHERN_MARIANA_ISLANDS":       164,
	"NORWAY":                         165,
	"OMAN":                           166,
	"PAKISTAN":                       167,
	"PALAU":                          168,
	"PANAMA":                         169,
	"PAPUA_NEW_GUINEA":               170,
	"PARAGUAY":                       171,
	"PERU":                           172,
	"PHILIPPINES":                    173,
	"PITCAIRN":                       174,
	"POLAND":                         175,
	"PORTUGAL":                       176,
	"PUERTO_RICO":                    177,
	"QATAR":                          178,
	"REUNION":                        179,
	"ROMANIA":                        180,
	"RUSSIA":                         181,
	"RWANDA":                         182,
	"SAINT_BARTHELEMY":               183,
	"SAINT_HELENA":                   184,
	"SAINT_KITTS":                    185,
	"SAINT_LUCIA":                    186,
	"SAINT_MARTIN":                   187,
	"SAINT_PIERRE":                   188,
	"SAINT_VINCENT":                  189,
	"SAMOA":                          190,
	"SAN_MARINO":                     191,
	"SAO_TOME":                       192,
	"SAUDI_ARABIA":                   193,
	"SENEGAL":                        194,
	"SERBIA":                         195,
	"SEYCHELLES":                     196,
	"SIERRA_LEONE":                   197,
	"SINGAPORE":                      198,
	"SINT_MAARTEN":                   199,
	"SUCRE":                          200,
	"SLOVAKIA":                       201,
	"SLOVENIA":                       202,
	"SOLOMON_ISLANDS":                203,
	"SOMALIA":                        204,
	"SOUTH_AFRICA":                   205,
	"SOUTH_SUDAN":                    206,
	"SPAIN":                          207,
	"SRI_LANKA":                      208,
	"SUDAN":                          209,
	"SURINAME":                       210,
	"SVALBARD":                       211,
	"ESWATINI":                       212,
	"SWAZILAND":                      212,
	"SWEDEN":                         213,
	"SWITZERLAND":                    214,
	"SYRIAN_ARAB_REPUBLIC":           215,
	"TAIWAN":                         216,
	"TAJIKISTAN":                     217,
	"TANZANIA":                       218,
	"THAILAND":                       219,
	"TIMOR_LESTE":                    220,
	"TOGO":                           221,
	"TOKELAU":                        222,
	"TONGA":                          223,
	"TRINIDAD":                       224,
	"TUNISIA":                        225,
	"TURKEY":                         226,
	"TURKMENISTAN":                   227,
	"TURKS_AND_CAICOS_ISLANDS":       228,
	"TUVALU":                         229,
	"UGANDA":                         230,
	"UKRAINE":                        231,
	"UNITED_ARAB_EMIRATES":           232,
	"UNITED_KINGDOM":                 233,
	"UNITED_STATES":                  234,
	"URUGUAY":                        235,
	"UZBEKISTAN":                     236,
	"VANUATU":                        237,
	"VENEZUELA":                      238,
	"VIETNAM":                        239,
	"VIRGIN_ISLANDS_BRITISH":         240,
	"VIRGIN_ISLANDS_US":              241,
	"WALLIS_AND_FUTUNA":              242,
	"WESTERN_SAHARA":                 243,
	"YEMEN":                          244,
	"ZAMBIA":                         245,
	"ZIMBABWE":                       246,
	"UNITED_STATES_MINOR_ISLANDS":    247,
	"ALL":                            500,
	"AFRICA":                         501,
	"ASIA":                           502,
	"CENTRAL_AMERICA":                503,
	"EUROPE":                         504,
	"MIDDLE_EAST":                    505,
	"NORTH_AMERICA":                  506,
	"SOUTH_AMERICA":                  507,
	"OCEANIA":                        508,
}

func (x CountryCode) String() string {
	return proto.EnumName(CountryCode_name, int32(x))
}
func (CountryCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_countrycodes_35efbc79bf99ad19, []int{0}
}

func init() {
	proto.RegisterEnum("CountryCode", CountryCode_name, CountryCode_value)
}

func init() { proto.RegisterFile("countrycodes.proto", fileDescriptor_countrycodes_35efbc79bf99ad19) }

var fileDescriptor_countrycodes_35efbc79bf99ad19 = []byte{
	// 2291 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x57, 0x65, 0xbc, 0x1c, 0xc7,
	0x91, 0xbf, 0xd5, 0x93, 0x05, 0x23, 0x2a, 0x8d, 0x65, 0x9d, 0x6d, 0x99, 0xce, 0x77, 0x17, 0x70,
	0x12, 0x07, 0x1c, 0xe6, 0x9a, 0x99, 0x7a, 0xb3, 0xf5, 0xb6, 0xa7, 0x7b, 0xd5, 0xb0, 0xeb, 0xdd,
	0xc0, 0x24, 0x86, 0x70, 0x2c, 0xc7, 0x90, 0xc4, 0x61, 0x66, 0x66, 0x66, 0xe6, 0xc4, 0x61, 0x66,
	0xe6, 0x38, 0xcc, 0xcc, 0x6c, 0x08, 0x7d, 0xc8, 0xaf, 0xaa, 0x47, 0x4f, 0x72, 0x3e, 0xed, 0x56,
	0x75, 0xe1, 0xbf, 0xaa, 0x6b, 0xaa, 0x8b, 0xf2, 0xcc, 0x03, 0x17, 0x9e, 0x73, 0xc1, 0x79, 0x17,
	0x9d, 0x79, 0xe0, 0xac, 0xb3, 0xcf, 0x3f, 0xf5, 0xdc, 0xf3, 0x0e, 0x5c, 0x70, 0xe0, 0x94, 0x8b,
	0x4f, 0x2c, 0xb6, 0xd5, 0x99, 0x5d, 0x1f, 0x38, 0xeb, 0xec, 0x72, 0x53, 0xb1, 0xc1, 0x22, 0xfc,
	0x57, 0xb9, 0xab, 0xd8, 0x86, 0xab, 0xed, 0x18, 0x2d, 0x87, 0x88, 0x16, 0x46, 0xe5, 0xee, 0x62,
	0x07, 0x1a, 0xb4, 0x4d, 0xcf, 0x41, 0x7e, 0x02, 0x6c, 0x28, 0xb7, 0x15, 0x9b, 0xd1, 0x54, 0x68,
	0x19, 0x61, 0x25, 0x13, 0x2d, 0x79, 0x46, 0xd8, 0x58, 0x96, 0xc5, 0x4e, 0xec, 0xc8, 0x73, 0x8d,
	0xb6, 0x0f, 0xd8, 0x39, 0x84, 0x23, 0x54, 0xc0, 0x36, 0xce, 0x7b, 0x84, 0x4d, 0x65, 0x51, 0x6c,
	0x42, 0xdb, 0x3a, 0x83, 0xb0, 0xb9, 0xdc, 0x5e, 0x6c, 0x41, 0xdb, 0x26, 0x36, 0x06, 0x61, 0x4b,
	0x16, 0x8b, 0xdc, 0x26, 0x84, 0xad, 0xe5, 0x8e, 0x62, 0x2b, 0xfa, 0x96, 0x6c, 0x64, 0x8b, 0x50,
	0xe8, 0x99, 0xef, 0x48, 0x1c, 0x6e, 0x2b, 0xb7, 0x16, 0x47, 0xa0, 0x4f, 0x15, 0xc2, 0x76, 0x15,
	0x4b, 0x21, 0x7a, 0x34, 0x8c, 0xb0, 0x43, 0xc5, 0x84, 0x64, 0x84, 0x9d, 0xe5, 0xce, 0xa2, 0xc0,
	0x25, 0xf9, 0x0a, 0x79, 0x0d, 0x2d, 0xec, 0x92, 0xc3, 0x0a, 0xc7, 0xd8, 0x61, 0x00, 0x18, 0x08,
	0x8f, 0x6c, 0x61, 0xb7, 0x48, 0x56, 0x68, 0x5b, 0x83, 0x0d, 0x85, 0x31, 0x94, 0x12, 0x57, 0x85,
	0xbe, 0xc2, 0xc6, 0x05, 0x38, 0x52, 0x45, 0xc9, 0xa0, 0x4f, 0x01, 0xf6, 0x0c, 0x44, 0xcb, 0xa9,
	0x83, 0xa3, 0x24, 0x97, 0x8a, 0x0c, 0x2f, 0x09, 0xf6, 0x4a, 0x50, 0x15, 0x59, 0xb6, 0xf0, 0xdf,
	0x59, 0xc6, 0x77, 0xa9, 0x41, 0x38, 0x5a, 0x65, 0xc6, 0x49, 0x90, 0x3c, 0x46, 0x0f, 0x9c, 0xe1,
	0x19, 0x23, 0x1c, 0x5b, 0x9e, 0x58, 0xec, 0xab, 0x9c, 0x45, 0xf6, 0xd4, 0x07, 0xb6, 0xb1, 0xa7,
	0x14, 0x22, 0x46, 0x4e, 0xa1, 0x0f, 0x58, 0x21, 0xec, 0x53, 0x4d, 0x17, 0x24, 0xe5, 0xe3, 0x34,
	0x22, 0x17, 0xc3, 0x1c, 0x2d, 0xc2, 0xf1, 0x52, 0x91, 0xca, 0xa5, 0x19, 0xc5, 0xa1, 0x24, 0x70,
	0x82, 0x0a, 0x7b, 0x5c, 0xb2, 0x81, 0x13, 0xcb, 0x93, 0x8b, 0x13, 0x2a, 0xcf, 0x91, 0xc3, 0xb8,
	0x67, 0xdb, 0x30, 0xda, 0xde, 0xd5, 0x84, 0xb6, 0x8f, 0xe4, 0x3d, 0x47, 0xe7, 0x17, 0x70, 0x52,
	0x79, 0x54, 0xb1, 0xbb, 0xf2, 0xc9, 0x12, 0xf7, 0x8d, 0x64, 0x16, 0xd0, 0x60, 0x07, 0xff, 0xa3,
	0x7e, 0x92, 0x69, 0x51, 0x10, 0x3c, 0xb9, 0x84, 0x62, 0x7b, 0x95, 0xfc, 0x84, 0x2d, 0xf6, 0xab,
	0x18, 0x1c, 0xfc, 0xaf, 0x66, 0x90, 0x7c, 0xb2, 0x0d, 0xc3, 0xff, 0x09, 0x6c, 0x35, 0x56, 0xae,
	0x9f, 0x91, 0x6f, 0x08, 0xfe, 0x5f, 0x94, 0x6b, 0xec, 0x2a, 0xd7, 0x30, 0xc2, 0x55, 0x06, 0x8a,
	0xbc, 0x73, 0x16, 0xae, 0x2a, 0xf1, 0xd5, 0x68, 0xb1, 0x41, 0xb8, 0x9a, 0xf4, 0x48, 0x8d, 0x8b,
	0x0e, 0xed, 0x7a, 0x47, 0x5d, 0xbd, 0x3c, 0xae, 0x38, 0xba, 0x26, 0x2b, 0x85, 0xec, 0x71, 0x35,
	0xb7, 0x8f, 0xa7, 0x69, 0xaa, 0x0c, 0xd7, 0x70, 0x4a, 0xb9, 0xa5, 0xd8, 0x58, 0x8f, 0xb1, 0x81,
	0x6b, 0x08, 0xcc, 0xf5, 0x98, 0x0d, 0xc1, 0x35, 0x87, 0xbf, 0x16, 0xe1, 0x5a, 0xe5, 0x9e, 0x02,
	0xea, 0xb1, 0xe7, 0x10, 0x3b, 0x0c, 0x07, 0x31, 0x39, 0x55, 0x60, 0xaa, 0x5d, 0xed, 0xc2, 0xba,
	0x9b, 0x6b, 0x6b, 0x50, 0xce, 0xb8, 0xae, 0x62, 0x84, 0xeb, 0x48, 0x36, 0xb5, 0xeb, 0x9c, 0x77,
	0x01, 0xae, 0xab, 0x51, 0x39, 0xdb, 0xba, 0x43, 0x7e, 0xaf, 0xa7, 0x2e, 0x84, 0x07, 0xa7, 0x09,
	0x16, 0xb5, 0x73, 0x93, 0x75, 0x5b, 0xd7, 0xd7, 0xf4, 0x5d, 0x88, 0xd8, 0x4b, 0xb8, 0x70, 0x83,
	0x2c, 0x11, 0xa9, 0x6f, 0x78, 0xe6, 0xd8, 0x13, 0xdc, 0x50, 0xed, 0x7b, 0x87, 0x91, 0x11, 0x6e,
	0xa4, 0x39, 0x48, 0xd3, 0xde, 0x58, 0xd9, 0xc9, 0x63, 0x8d, 0x0e, 0x6e, 0xa2, 0xc0, 0x2c, 0xa6,
	0xd2, 0x5c, 0x37, 0xd5, 0x10, 0x96, 0x54, 0x8f, 0x0f, 0x85, 0x70, 0x33, 0x11, 0x6e, 0xc8, 0x76,
	0xe8, 0x27, 0x70, 0x73, 0x09, 0xbf, 0x59, 0xe3, 0xca, 0xa5, 0xc8, 0x70, 0x0b, 0xa5, 0x5c, 0xc7,
	0x56, 0xdc, 0xdf, 0xb2, 0xdc, 0x5b, 0x94, 0x07, 0xa9, 0xc3, 0xb0, 0xbb, 0x95, 0x18, 0xa0, 0x3a,
	0x61, 0xe3, 0x3c, 0xdc, 0x5a, 0x12, 0xa2, 0x76, 0x31, 0x8d, 0x80, 0x72, 0xcf, 0xc9, 0xf4, 0x01,
	0xcd, 0x4c, 0xcf, 0x2a, 0x69, 0x09, 0xda, 0x9f, 0x30, 0x3a, 0xcf, 0x68, 0xfa, 0x36, 0xb1, 0x25,
	0x84, 0x5a, 0xf5, 0x3d, 0x47, 0x4f, 0x08, 0x8d, 0x12, 0x21, 0x3a, 0x69, 0x4a, 0x12, 0xff, 0x14,
	0xc7, 0xec, 0xa6, 0x8c, 0xb0, 0x2a, 0x35, 0x58, 0x45, 0x33, 0xb9, 0xd2, 0xa4, 0x68, 0xa5, 0x06,
	0xab, 0xe8, 0x1d, 0xad, 0xb3, 0xc6, 0x02, 0xc4, 0x2a, 0xaf, 0x31, 0xb0, 0x58, 0x5b, 0x65, 0xab,
	0xd5, 0x5a, 0x13, 0x20, 0x56, 0x3d, 0xda, 0x9a, 0x60, 0xa2, 0x5a, 0x9e, 0x6c, 0x3d, 0x96, 0x30,
	0xa4, 0xe7, 0x8d, 0x9a, 0xcf, 0xac, 0xa9, 0x33, 0x0b, 0x4b, 0x81, 0x11, 0x3a, 0xb9, 0x44, 0x03,
	0x37, 0xb8, 0x14, 0xc7, 0xe4, 0x0f, 0x75, 0x39, 0x53, 0x00, 0x2b, 0x09, 0xb7, 0x58, 0x39, 0x0b,
	0x4e, 0x1c, 0xb4, 0xa8, 0x95, 0x9f, 0x8a, 0xe7, 0x96, 0x9c, 0x6f, 0x19, 0x61, 0x7f, 0x26, 0x7c,
	0x87, 0x76, 0x01, 0x5e, 0x15, 0xc6, 0xe2, 0x32, 0xc8, 0x70, 0x69, 0xb9, 0xf2, 0x68, 0x22, 0x7a,
	0x88, 0xaa, 0xef, 0x89, 0x6a, 0x82, 0xa4, 0x47, 0x9e, 0x28, 0xc7, 0x3e, 0x53, 0x0b, 0x9e, 0xb4,
	0xbd, 0xe7, 0xd2, 0x17, 0x6d, 0xc2, 0x86, 0x8c, 0x4b, 0x53, 0x82, 0xd3, 0x25, 0xdf, 0x36, 0x61,
	0x07, 0x0b, 0xd5, 0x4a, 0x18, 0xa9, 0x43, 0x83, 0xb0, 0x14, 0xfc, 0xda, 0x44, 0xde, 0x06, 0x5a,
	0xc0, 0x6d, 0xd4, 0x7c, 0xc6, 0xfc, 0xb6, 0x92, 0x7f, 0xfe, 0xdf, 0x57, 0x1c, 0x02, 0x26, 0xb8,
	0x5d, 0x3e, 0x5e, 0x48, 0x60, 0xb7, 0x97, 0x18, 0xc7, 0xc8, 0x91, 0xa1, 0x97, 0xa6, 0x1b, 0x13,
	0xfa, 0x83, 0x90, 0xc3, 0x1d, 0xc4, 0xea, 0xd8, 0x99, 0x45, 0x1f, 0x88, 0xe0, 0x8e, 0x99, 0xb2,
	0x4d, 0xf2, 0x18, 0xe0, 0x0c, 0x09, 0x60, 0xec, 0x6c, 0xdb, 0x4f, 0x9c, 0x6d, 0xe1, 0x4c, 0x09,
	0x7b, 0x9c, 0x6c, 0x8b, 0x7e, 0x01, 0x67, 0x09, 0xc1, 0x35, 0xa9, 0x91, 0xb3, 0xc5, 0x83, 0x8e,
	0x0e, 0xb8, 0x93, 0xe8, 0xb0, 0x6d, 0x5c, 0x46, 0xfc, 0xce, 0x92, 0x0d, 0x7b, 0xb4, 0x70, 0x97,
	0xe1, 0xdf, 0x7e, 0xb8, 0xab, 0xaa, 0xfa, 0xac, 0x7a, 0x37, 0xe9, 0x2b, 0x0e, 0x86, 0x7a, 0xb7,
	0xda, 0x77, 0x68, 0xe1, 0xee, 0x12, 0x39, 0x07, 0x8f, 0x64, 0xe0, 0x1e, 0x6a, 0x37, 0xa2, 0x59,
	0xc0, 0x3d, 0x45, 0x69, 0x0d, 0x3b, 0x94, 0xe6, 0x3d, 0x47, 0xf8, 0x6b, 0x38, 0x45, 0x0b, 0x07,
	0x44, 0x7c, 0x8d, 0xbc, 0x60, 0x72, 0xae, 0xfe, 0x77, 0xbe, 0x41, 0x0b, 0xf7, 0x12, 0x58, 0x27,
	0xb8, 0xc4, 0xc9, 0x58, 0x3f, 0x4b, 0xe7, 0x89, 0xca, 0x84, 0xec, 0x02, 0xe1, 0x7c, 0x49, 0x72,
	0xc2, 0x9e, 0x2b, 0x8c, 0x0c, 0x17, 0x48, 0x00, 0xd6, 0xf9, 0x38, 0xee, 0x27, 0x4e, 0x9a, 0xf6,
	0x42, 0x61, 0x68, 0x77, 0x0c, 0x8c, 0x7b, 0x8b, 0xd9, 0x49, 0x9a, 0x23, 0x47, 0xb8, 0x8f, 0x9a,
	0x5d, 0xf8, 0x76, 0xb1, 0x54, 0xb3, 0xf7, 0x2d, 0x37, 0x17, 0x2b, 0x06, 0x1d, 0x5c, 0x24, 0x42,
	0x06, 0xa3, 0xcc, 0xea, 0xfb, 0x49, 0xac, 0x86, 0x2a, 0xb4, 0xce, 0xc2, 0xfd, 0x33, 0x11, 0x5c,
	0x1c, 0x3b, 0x78, 0x80, 0x12, 0x5c, 0xe9, 0xc7, 0xef, 0x81, 0x12, 0x92, 0xe1, 0x6a, 0x81, 0xf0,
	0x20, 0xa9, 0xa0, 0x61, 0xaa, 0xc7, 0x91, 0x6c, 0x88, 0xc4, 0x16, 0x1e, 0x5c, 0xee, 0x2c, 0xb6,
	0x1a, 0x8e, 0xe3, 0xa4, 0x9f, 0xcd, 0x87, 0x8c, 0xca, 0x5d, 0x45, 0x61, 0xd2, 0xe9, 0xd4, 0x55,
	0x2e, 0xf9, 0x16, 0x1e, 0x3a, 0x2a, 0x8b, 0xe2, 0x88, 0x4e, 0xa7, 0xc2, 0xc3, 0x46, 0x22, 0xdc,
	0x61, 0x4d, 0x8d, 0x5e, 0xb5, 0x87, 0xab, 0x70, 0x87, 0x0d, 0xb6, 0x18, 0x6a, 0xf4, 0xf0, 0x88,
	0x51, 0xb9, 0xad, 0xd8, 0x24, 0x6d, 0x34, 0x67, 0x78, 0xe4, 0xa8, 0xdc, 0x51, 0x6c, 0x11, 0x62,
	0x21, 0x25, 0x7a, 0xd4, 0x41, 0xb2, 0xe1, 0x19, 0x05, 0x78, 0xf4, 0xa8, 0xdc, 0x5a, 0x6c, 0xec,
	0xd0, 0x30, 0x3c, 0x66, 0x70, 0x61, 0x22, 0xc2, 0x63, 0x47, 0xe5, 0x51, 0x05, 0x74, 0xe8, 0xc3,
	0x18, 0x8d, 0x59, 0xbf, 0x9d, 0x8f, 0x1b, 0x3c, 0xf9, 0xc8, 0x96, 0xf7, 0x27, 0x82, 0xc7, 0x0f,
	0x8c, 0xe4, 0x39, 0x6a, 0xe0, 0x4f, 0x18, 0x62, 0x13, 0x06, 0xa7, 0x00, 0x4f, 0x1c, 0x95, 0xdb,
	0x8b, 0xcd, 0x1d, 0x2e, 0x5c, 0x8c, 0x04, 0x4f, 0xca, 0x81, 0xd1, 0xe9, 0x5c, 0x3b, 0x78, 0x72,
	0xd6, 0xe5, 0xda, 0x0f, 0xdd, 0xf3, 0x94, 0x2c, 0xeb, 0x4c, 0xe3, 0x66, 0x08, 0x4f, 0xcd, 0xb2,
	0xce, 0x62, 0xed, 0xe0, 0x69, 0x39, 0x6a, 0x19, 0xb6, 0xf2, 0x29, 0x7f, 0x7a, 0x56, 0x75, 0x36,
	0x92, 0xa5, 0xd6, 0x3b, 0x78, 0xc6, 0x3a, 0x23, 0x90, 0xf7, 0x18, 0xe1, 0x99, 0x83, 0x2d, 0xef,
	0xea, 0xda, 0xc1, 0xb3, 0x86, 0xe3, 0xa5, 0x5c, 0x70, 0x89, 0xfb, 0xd9, 0xf9, 0x78, 0x81, 0x32,
	0x3a, 0xe1, 0x39, 0x4a, 0x59, 0xec, 0x58, 0xae, 0xff, 0x73, 0x15, 0x07, 0x8b, 0xc9, 0x27, 0x78,
	0x5e, 0xfe, 0x4f, 0x53, 0x34, 0xf0, 0xfc, 0x51, 0x09, 0xc5, 0x36, 0x4b, 0x32, 0x47, 0x32, 0x1c,
	0x2f, 0x18, 0x95, 0x65, 0xb1, 0xc3, 0xd2, 0xbc, 0xaf, 0xd1, 0x0c, 0xc5, 0x78, 0xe1, 0x20, 0x35,
	0xef, 0x97, 0xa4, 0x7b, 0x11, 0xbc, 0x48, 0x21, 0x91, 0xc1, 0xeb, 0x51, 0xb6, 0x97, 0x17, 0x67,
	0x9b, 0xdc, 0x92, 0x87, 0x97, 0x64, 0xcf, 0x9c, 0xf7, 0xa3, 0x97, 0x6a, 0x31, 0x2c, 0x27, 0x82,
	0x97, 0x8d, 0xca, 0x23, 0x8b, 0x9d, 0xd6, 0xf9, 0x55, 0x67, 0x0e, 0x7e, 0x55, 0xe0, 0xe5, 0xa3,
	0xf2, 0xf8, 0xe2, 0x68, 0xed, 0x5e, 0x19, 0x65, 0x9d, 0x7c, 0x87, 0x2d, 0xae, 0x57, 0xe7, 0x15,
	0x8a, 0x98, 0x75, 0x7e, 0x8e, 0x0b, 0x78, 0xa5, 0xda, 0x72, 0x72, 0xc7, 0x5e, 0xa5, 0xe0, 0x4d,
	0x71, 0x92, 0x57, 0xb6, 0x57, 0xab, 0xff, 0x29, 0x1a, 0x4c, 0xf0, 0x1a, 0x55, 0x99, 0xa2, 0xc5,
	0x0e, 0xe1, 0xb5, 0x5a, 0xf4, 0x29, 0x4e, 0x13, 0xf6, 0x92, 0xc0, 0x30, 0x6f, 0x5e, 0x37, 0xa8,
	0x6b, 0xf4, 0x0b, 0x78, 0xbd, 0x1a, 0x9e, 0x92, 0x4f, 0xf0, 0x06, 0xcd, 0x75, 0x3a, 0x66, 0xc3,
	0xd3, 0x29, 0x5b, 0x0a, 0xf0, 0xc6, 0x2c, 0xcb, 0xb1, 0x46, 0xf6, 0x16, 0xde, 0x94, 0xcd, 0x3b,
	0x8d, 0xfe, 0xcd, 0xf9, 0xcc, 0xf9, 0x98, 0x5a, 0x34, 0xf0, 0x96, 0xac, 0x9c, 0xc8, 0x47, 0x27,
	0xdf, 0x48, 0x07, 0x6f, 0xd5, 0xc0, 0xf6, 0xa3, 0xcc, 0xd3, 0xb7, 0x29, 0x30, 0x9e, 0x92, 0x65,
	0x67, 0xe1, 0xe2, 0x4c, 0x49, 0x36, 0x8c, 0xf0, 0x76, 0xb5, 0x2a, 0x6b, 0x09, 0x23, 0xbc, 0x23,
	0x13, 0x73, 0xb4, 0x0d, 0xc2, 0x3b, 0x35, 0x83, 0x80, 0xb2, 0x30, 0x55, 0x28, 0x30, 0x19, 0xea,
	0x16, 0xf0, 0x2e, 0xd9, 0x52, 0xb7, 0x67, 0xb6, 0xb0, 0x2c, 0xc2, 0xbb, 0xd5, 0x7b, 0x66, 0x4d,
	0x38, 0xc6, 0x00, 0xef, 0x39, 0x8c, 0x63, 0x52, 0xcd, 0x08, 0xef, 0x3d, 0x4c, 0x2d, 0xf7, 0x3c,
	0xbc, 0xef, 0x30, 0xd6, 0x94, 0xc9, 0x7b, 0x82, 0xf7, 0x6b, 0x13, 0x64, 0xd6, 0x8c, 0xad, 0xac,
	0x29, 0xf0, 0x01, 0xcd, 0x24, 0x2f, 0xb8, 0x1f, 0xd4, 0xde, 0x0b, 0x98, 0xeb, 0x65, 0x1d, 0x7c,
	0x48, 0x71, 0x08, 0xe8, 0xfa, 0xe8, 0x3a, 0x82, 0x0f, 0x0f, 0x26, 0x53, 0xc3, 0x3d, 0x7a, 0x94,
	0x0e, 0xfc, 0x88, 0xa6, 0x1b, 0xa4, 0xb7, 0xd1, 0xc0, 0x47, 0x35, 0xc3, 0x40, 0x5e, 0x8e, 0x3e,
	0x96, 0xad, 0xd1, 0xa2, 0x1e, 0x93, 0x31, 0x14, 0xe0, 0xe3, 0x59, 0x5d, 0x62, 0xc1, 0xde, 0x90,
	0xb3, 0x04, 0x9f, 0xd0, 0x86, 0x0b, 0x6c, 0x5b, 0x9c, 0x3a, 0x4f, 0xf0, 0xc9, 0x41, 0x44, 0xd3,
	0x40, 0x1f, 0xc9, 0xc2, 0xa7, 0x72, 0x80, 0xa9, 0xf6, 0x04, 0x9f, 0xce, 0xf1, 0x18, 0x37, 0xc3,
	0x09, 0x23, 0x7c, 0x66, 0x9d, 0xd4, 0x7d, 0xfa, 0xb3, 0xa3, 0x72, 0x4f, 0xb1, 0x2b, 0xc8, 0x56,
	0xe4, 0x0e, 0x6d, 0x64, 0x9f, 0xcb, 0x11, 0xba, 0x4e, 0x37, 0xeb, 0xcf, 0x67, 0x07, 0x3a, 0x44,
	0xf3, 0x7a, 0x06, 0x5f, 0xc8, 0x68, 0x2a, 0x2b, 0x24, 0x19, 0xd1, 0x5f, 0xcc, 0x2e, 0xa7, 0xb2,
	0x53, 0x7f, 0x29, 0x47, 0xe8, 0xb9, 0x37, 0x68, 0x27, 0x08, 0x5f, 0x1e, 0xc2, 0x11, 0xb9, 0xaf,
	0x64, 0xff, 0xc9, 0xb3, 0xc5, 0x8e, 0xe0, 0xab, 0x99, 0x9c, 0xc9, 0x83, 0xc2, 0x37, 0xf0, 0x35,
	0x25, 0x29, 0xcc, 0x51, 0x46, 0x10, 0x5c, 0x92, 0x0d, 0xcd, 0x65, 0xb5, 0x95, 0x1e, 0xbb, 0x24,
	0x63, 0x35, 0xa7, 0x86, 0x2c, 0x7c, 0x3d, 0xc7, 0x30, 0xe7, 0xb8, 0xcc, 0x37, 0x16, 0xbe, 0x31,
	0x2a, 0x8f, 0x29, 0xf6, 0x84, 0x85, 0xdc, 0x1b, 0x05, 0xfb, 0xd0, 0x26, 0xf4, 0x4d, 0xd5, 0x8c,
	0xc8, 0x73, 0xb4, 0xf0, 0x2d, 0x45, 0x39, 0xe2, 0x1a, 0x0f, 0x77, 0xe6, 0xdb, 0xea, 0x36, 0xa2,
	0x5d, 0x6a, 0x07, 0x7e, 0x27, 0x93, 0x63, 0xcc, 0x5e, 0xbf, 0xab, 0x8e, 0x22, 0x77, 0xce, 0xf7,
	0x86, 0x42, 0x24, 0xf8, 0x9e, 0x5e, 0x92, 0xe8, 0x5a, 0x07, 0xdf, 0x57, 0xa8, 0xa2, 0x9b, 0x90,
	0x5c, 0xb8, 0x1f, 0x68, 0xa6, 0xd1, 0xd9, 0x16, 0xe1, 0x87, 0xd9, 0x8a, 0x67, 0xcb, 0x0d, 0x36,
	0xf0, 0xa3, 0x2c, 0x98, 0x2c, 0x4b, 0x5f, 0xff, 0x38, 0xc7, 0x93, 0xfc, 0x84, 0x16, 0xf0, 0x13,
	0x05, 0x58, 0x08, 0x79, 0xe4, 0x68, 0x44, 0x3f, 0xd5, 0x59, 0x20, 0xac, 0xd0, 0xcb, 0x4e, 0x55,
	0x23, 0x1f, 0xbe, 0xcb, 0xfe, 0x6c, 0x50, 0x9f, 0xa1, 0x49, 0xf0, 0x73, 0x25, 0x52, 0xab, 0x77,
	0xe4, 0x17, 0xea, 0x26, 0x4d, 0xe4, 0x71, 0x43, 0xf0, 0x4b, 0x45, 0x24, 0x59, 0x8e, 0xd4, 0x64,
	0x44, 0xa8, 0x63, 0x8f, 0x91, 0x02, 0xfc, 0x4a, 0x47, 0xd0, 0x70, 0x34, 0x61, 0xdb, 0x36, 0xae,
	0x83, 0x5f, 0x6b, 0xb7, 0x0f, 0x4c, 0x79, 0x91, 0x50, 0x80, 0xdf, 0x64, 0x8b, 0x3e, 0xe9, 0x7c,
	0xf8, 0xad, 0x62, 0x97, 0x96, 0x15, 0x0d, 0xd8, 0xfd, 0x4e, 0x8f, 0x67, 0x68, 0x13, 0xc6, 0x04,
	0xbf, 0xd7, 0x8a, 0xcd, 0xc8, 0xd2, 0x32, 0x91, 0x41, 0xf8, 0x43, 0x3e, 0x65, 0x8a, 0x16, 0x3b,
	0xf8, 0xe3, 0xa8, 0xdc, 0x57, 0xec, 0x9d, 0xb1, 0x6f, 0x79, 0xbd, 0xd9, 0xfa, 0xe1, 0xb5, 0x02,
	0x7f, 0x1a, 0x95, 0x7b, 0x8b, 0xdd, 0xff, 0x71, 0x98, 0x02, 0xfc, 0x59, 0xf9, 0x73, 0x34, 0x86,
	0x33, 0x16, 0xab, 0x29, 0x26, 0x8b, 0xf0, 0x17, 0x4d, 0x60, 0x2e, 0x05, 0xf1, 0xf2, 0xdc, 0x1c,
	0xa3, 0x47, 0xf8, 0xab, 0x16, 0x60, 0x41, 0x1d, 0x59, 0xb8, 0x54, 0x71, 0x59, 0xe6, 0xad, 0xef,
	0x32, 0xad, 0xc6, 0x92, 0xbb, 0x0a, 0xab, 0x39, 0xc1, 0xe5, 0xa3, 0xf2, 0xa4, 0x62, 0xdf, 0x95,
	0x12, 0xed, 0x3b, 0xb6, 0xce, 0xaf, 0x43, 0x7c, 0xc5, 0xa8, 0xdc, 0x52, 0xac, 0xa0, 0x31, 0x70,
	0xa9, 0xbc, 0x72, 0x37, 0x0d, 0x9d, 0x7f, 0xd9, 0x8a, 0x94, 0x1e, 0xa5, 0x86, 0x97, 0xaf, 0xc8,
	0xdd, 0x59, 0x7f, 0xb8, 0xe4, 0x87, 0x2f, 0x5c, 0xa1, 0xd2, 0x94, 0xbc, 0x9b, 0x12, 0xfc, 0x6d,
	0x45, 0x5a, 0xa7, 0xe3, 0xa6, 0x31, 0xd4, 0x13, 0x86, 0x08, 0x7f, 0x5f, 0xd1, 0x8f, 0x8a, 0xae,
	0x28, 0x07, 0x55, 0xfe, 0xa1, 0xbc, 0xe1, 0x82, 0x0d, 0xbc, 0x7f, 0xae, 0x08, 0x70, 0xfa, 0x74,
	0x63, 0x84, 0x7f, 0xad, 0x1c, 0xbb, 0x01, 0x46, 0xd5, 0xc6, 0xe5, 0x86, 0x73, 0xcf, 0x38, 0x63,
	0x93, 0x3e, 0xe1, 0x4f, 0xfb, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x7b, 0x44, 0x60, 0x36, 0xd8,
	0x0f, 0x00, 0x00,
}
