// Code generated by protoc-gen-go.
// source: message.proto
// DO NOT EDIT!

/*
Package message is a generated protocol buffer package.

It is generated from these files:
	message.proto

It has these top-level messages:
	Message
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type Message_MessageType int32

const (
	Message_PING Message_MessageType = 0
)

var Message_MessageType_name = map[int32]string{
	0: "PING",
}
var Message_MessageType_value = map[string]int32{
	"PING": 0,
}

func (x Message_MessageType) String() string {
	return proto.EnumName(Message_MessageType_name, int32(x))
}
func (Message_MessageType) EnumDescriptor() ([]byte, []int) { return fileDescriptor2, []int{0, 0} }

type Message struct {
	MessageType Message_MessageType `protobuf:"varint,1,opt,name=messageType,enum=Message_MessageType" json:"messageType,omitempty"`
	Arguments   []string            `protobuf:"bytes,2,rep,name=arguments" json:"arguments,omitempty"`
}

func (m *Message) Reset()                    { *m = Message{} }
func (m *Message) String() string            { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()               {}
func (*Message) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

func init() {
	proto.RegisterType((*Message)(nil), "Message")
	proto.RegisterEnum("Message_MessageType", Message_MessageType_name, Message_MessageType_value)
}

var fileDescriptor2 = []byte{
	// 117 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0xcd, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0xaa, 0xe0, 0x62, 0xf7, 0x85, 0x08,
	0x08, 0x99, 0x71, 0x71, 0x43, 0xe5, 0x42, 0x2a, 0x0b, 0x52, 0x25, 0x18, 0x15, 0x18, 0x35, 0xf8,
	0x8c, 0x44, 0xf4, 0xa0, 0xd2, 0x30, 0x1a, 0x24, 0x17, 0x84, 0xac, 0x50, 0x48, 0x86, 0x8b, 0x33,
	0xb1, 0x28, 0xbd, 0x34, 0x37, 0x35, 0xaf, 0xa4, 0x58, 0x82, 0x49, 0x81, 0x59, 0x83, 0x33, 0x08,
	0x21, 0xa0, 0x24, 0xce, 0xc5, 0x8d, 0xa4, 0x53, 0x88, 0x83, 0x8b, 0x25, 0xc0, 0xd3, 0xcf, 0x5d,
	0x80, 0x21, 0x89, 0x0d, 0xec, 0x00, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xbc, 0x4d, 0x93,
	0x23, 0x91, 0x00, 0x00, 0x00,
}
