// Code generated by protoc-gen-go.
// source: orders.proto
// DO NOT EDIT!

/*
Package orders is a generated protocol buffer package.

It is generated from these files:
	orders.proto

It has these top-level messages:
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type OrderState int32

const (
	// New order, has not yet been accepted by the vendor
	OrderState_PENDING OrderState = 0
	// Vendor has accepted the order and is awaiting payment
	OrderState_CONFIRMED OrderState = 1
	// Buyer has funded the order
	OrderState_FUNDED OrderState = 2
	// Vendor has shipped the item/sent the digitial good
	OrderState_FULFILLED OrderState = 3
	// Buyer has completed the order, released the funds, and left a review
	OrderState_COMPLETE OrderState = 4
	// Contract is under active dispute
	OrderState_DISPUTED OrderState = 5
	// The moderator has resolved the dispute and we are waiting for the winning party to
	// accept the payout. After the payout is accepted the state will be set to COMPLETE
	OrderState_RESOLVED OrderState = 6
	// Vendor refunded the order
	OrderState_REFUNDED OrderState = 7
	// Buyer canceled the order (offline order only)
	OrderState_CANCELED OrderState = 8
	// Vendor declined to confirm the order (offline order only)
	OrderState_REJECTED OrderState = 9
)

var OrderState_name = map[int32]string{
	0: "PENDING",
	1: "CONFIRMED",
	2: "FUNDED",
	3: "FULFILLED",
	4: "COMPLETE",
	5: "DISPUTED",
	6: "RESOLVED",
	7: "REFUNDED",
	8: "CANCELED",
	9: "REJECTED",
}
var OrderState_value = map[string]int32{
	"PENDING":   0,
	"CONFIRMED": 1,
	"FUNDED":    2,
	"FULFILLED": 3,
	"COMPLETE":  4,
	"DISPUTED":  5,
	"RESOLVED":  6,
	"REFUNDED":  7,
	"CANCELED":  8,
	"REJECTED":  9,
}

func (x OrderState) String() string {
	return proto.EnumName(OrderState_name, int32(x))
}
func (OrderState) EnumDescriptor() ([]byte, []int) { return fileDescriptor6, []int{0} }

func init() {
	proto.RegisterEnum("OrderState", OrderState_name, OrderState_value)
}

var fileDescriptor6 = []byte{
	// 163 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x2c, 0x8e, 0x4d, 0x0e, 0xc2, 0x20,
	0x10, 0x85, 0xad, 0x3f, 0xfd, 0x19, 0x6b, 0xd2, 0x70, 0x0c, 0x17, 0x6e, 0x3c, 0x81, 0x81, 0xc1,
	0x60, 0x28, 0x34, 0x6d, 0x71, 0xaf, 0xb1, 0x6b, 0x0c, 0x72, 0x17, 0xaf, 0x2b, 0xd3, 0xba, 0x9b,
	0x6f, 0xbe, 0xbc, 0x97, 0x07, 0xb5, 0x0f, 0xaf, 0x29, 0x7c, 0x4e, 0xef, 0xe0, 0xa3, 0x3f, 0x7e,
	0x33, 0x00, 0x4b, 0x8f, 0x21, 0x3e, 0xe2, 0xc4, 0xf6, 0x50, 0x74, 0x68, 0x84, 0x32, 0xd7, 0x66,
	0xc5, 0x0e, 0x50, 0x71, 0x6b, 0xa4, 0xea, 0x5b, 0x14, 0x4d, 0xc6, 0x00, 0x72, 0xe9, 0x8c, 0x48,
	0xf7, 0x9a, 0x94, 0x74, 0x5a, 0x2a, 0xad, 0x13, 0x6e, 0x58, 0x0d, 0x25, 0xb7, 0x6d, 0xa7, 0x71,
	0xc4, 0x66, 0x4b, 0x24, 0xd4, 0xd0, 0xb9, 0x31, 0xb9, 0x1d, 0x51, 0x8f, 0x83, 0xd5, 0xf7, 0x44,
	0xf9, 0x42, 0xff, 0x9a, 0x62, 0xce, 0x5d, 0x0c, 0x47, 0x6a, 0x29, 0x17, 0x77, 0x43, 0x4e, 0xb9,
	0xea, 0x99, 0xcf, 0x03, 0xcf, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x65, 0x3f, 0x75, 0x01, 0xb0,
	0x00, 0x00, 0x00,
}
