// Code generated by protoc-gen-go.
// source: profile.proto
// DO NOT EDIT!

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Profile struct {
	PeerID           string                     `protobuf:"bytes,1,opt,name=peerID" json:"peerID,omitempty"`
	Handle           string                     `protobuf:"bytes,2,opt,name=handle" json:"handle,omitempty"`
	Name             string                     `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	Location         string                     `protobuf:"bytes,4,opt,name=location" json:"location,omitempty"`
	About            string                     `protobuf:"bytes,5,opt,name=about" json:"about,omitempty"`
	ShortDescription string                     `protobuf:"bytes,6,opt,name=shortDescription" json:"shortDescription,omitempty"`
	Nsfw             bool                       `protobuf:"varint,7,opt,name=nsfw" json:"nsfw,omitempty"`
	Vendor           bool                       `protobuf:"varint,8,opt,name=vendor" json:"vendor,omitempty"`
	Moderator        bool                       `protobuf:"varint,9,opt,name=moderator" json:"moderator,omitempty"`
	ModeratorInfo    *Moderator                 `protobuf:"bytes,10,opt,name=moderatorInfo" json:"moderatorInfo,omitempty"`
	ContactInfo      *Profile_Contact           `protobuf:"bytes,11,opt,name=contactInfo" json:"contactInfo,omitempty"`
	Colors           *Profile_Colors            `protobuf:"bytes,12,opt,name=colors" json:"colors,omitempty"`
	AvatarHashes     *Profile_Image             `protobuf:"bytes,13,opt,name=avatarHashes" json:"avatarHashes,omitempty"`
	HeaderHashes     *Profile_Image             `protobuf:"bytes,14,opt,name=headerHashes" json:"headerHashes,omitempty"`
	Stats            *Profile_Stats             `protobuf:"bytes,15,opt,name=stats" json:"stats,omitempty"`
	BitcoinPubkey    string                     `protobuf:"bytes,16,opt,name=bitcoinPubkey" json:"bitcoinPubkey,omitempty"`
	LastModified     *google_protobuf.Timestamp `protobuf:"bytes,17,opt,name=lastModified" json:"lastModified,omitempty"`
}

func (m *Profile) Reset()                    { *m = Profile{} }
func (m *Profile) String() string            { return proto.CompactTextString(m) }
func (*Profile) ProtoMessage()               {}
func (*Profile) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{0} }

func (m *Profile) GetPeerID() string {
	if m != nil {
		return m.PeerID
	}
	return ""
}

func (m *Profile) GetHandle() string {
	if m != nil {
		return m.Handle
	}
	return ""
}

func (m *Profile) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Profile) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *Profile) GetAbout() string {
	if m != nil {
		return m.About
	}
	return ""
}

func (m *Profile) GetShortDescription() string {
	if m != nil {
		return m.ShortDescription
	}
	return ""
}

func (m *Profile) GetNsfw() bool {
	if m != nil {
		return m.Nsfw
	}
	return false
}

func (m *Profile) GetVendor() bool {
	if m != nil {
		return m.Vendor
	}
	return false
}

func (m *Profile) GetModerator() bool {
	if m != nil {
		return m.Moderator
	}
	return false
}

func (m *Profile) GetModeratorInfo() *Moderator {
	if m != nil {
		return m.ModeratorInfo
	}
	return nil
}

func (m *Profile) GetContactInfo() *Profile_Contact {
	if m != nil {
		return m.ContactInfo
	}
	return nil
}

func (m *Profile) GetColors() *Profile_Colors {
	if m != nil {
		return m.Colors
	}
	return nil
}

func (m *Profile) GetAvatarHashes() *Profile_Image {
	if m != nil {
		return m.AvatarHashes
	}
	return nil
}

func (m *Profile) GetHeaderHashes() *Profile_Image {
	if m != nil {
		return m.HeaderHashes
	}
	return nil
}

func (m *Profile) GetStats() *Profile_Stats {
	if m != nil {
		return m.Stats
	}
	return nil
}

func (m *Profile) GetBitcoinPubkey() string {
	if m != nil {
		return m.BitcoinPubkey
	}
	return ""
}

func (m *Profile) GetLastModified() *google_protobuf.Timestamp {
	if m != nil {
		return m.LastModified
	}
	return nil
}

type Profile_Contact struct {
	Website     string                   `protobuf:"bytes,1,opt,name=website" json:"website,omitempty"`
	Email       string                   `protobuf:"bytes,2,opt,name=email" json:"email,omitempty"`
	PhoneNumber string                   `protobuf:"bytes,3,opt,name=phoneNumber" json:"phoneNumber,omitempty"`
	Social      []*Profile_SocialAccount `protobuf:"bytes,4,rep,name=social" json:"social,omitempty"`
}

func (m *Profile_Contact) Reset()                    { *m = Profile_Contact{} }
func (m *Profile_Contact) String() string            { return proto.CompactTextString(m) }
func (*Profile_Contact) ProtoMessage()               {}
func (*Profile_Contact) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{0, 0} }

func (m *Profile_Contact) GetWebsite() string {
	if m != nil {
		return m.Website
	}
	return ""
}

func (m *Profile_Contact) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Profile_Contact) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *Profile_Contact) GetSocial() []*Profile_SocialAccount {
	if m != nil {
		return m.Social
	}
	return nil
}

type Profile_SocialAccount struct {
	Type     string `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
	Username string `protobuf:"bytes,2,opt,name=username" json:"username,omitempty"`
	Proof    string `protobuf:"bytes,3,opt,name=proof" json:"proof,omitempty"`
}

func (m *Profile_SocialAccount) Reset()                    { *m = Profile_SocialAccount{} }
func (m *Profile_SocialAccount) String() string            { return proto.CompactTextString(m) }
func (*Profile_SocialAccount) ProtoMessage()               {}
func (*Profile_SocialAccount) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{0, 1} }

func (m *Profile_SocialAccount) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Profile_SocialAccount) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Profile_SocialAccount) GetProof() string {
	if m != nil {
		return m.Proof
	}
	return ""
}

type Profile_Image struct {
	Tiny     string `protobuf:"bytes,1,opt,name=tiny" json:"tiny,omitempty"`
	Small    string `protobuf:"bytes,2,opt,name=small" json:"small,omitempty"`
	Medium   string `protobuf:"bytes,3,opt,name=medium" json:"medium,omitempty"`
	Large    string `protobuf:"bytes,4,opt,name=large" json:"large,omitempty"`
	Original string `protobuf:"bytes,5,opt,name=original" json:"original,omitempty"`
}

func (m *Profile_Image) Reset()                    { *m = Profile_Image{} }
func (m *Profile_Image) String() string            { return proto.CompactTextString(m) }
func (*Profile_Image) ProtoMessage()               {}
func (*Profile_Image) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{0, 2} }

func (m *Profile_Image) GetTiny() string {
	if m != nil {
		return m.Tiny
	}
	return ""
}

func (m *Profile_Image) GetSmall() string {
	if m != nil {
		return m.Small
	}
	return ""
}

func (m *Profile_Image) GetMedium() string {
	if m != nil {
		return m.Medium
	}
	return ""
}

func (m *Profile_Image) GetLarge() string {
	if m != nil {
		return m.Large
	}
	return ""
}

func (m *Profile_Image) GetOriginal() string {
	if m != nil {
		return m.Original
	}
	return ""
}

type Profile_Colors struct {
	Primary       string `protobuf:"bytes,1,opt,name=primary" json:"primary,omitempty"`
	Secondary     string `protobuf:"bytes,2,opt,name=secondary" json:"secondary,omitempty"`
	Text          string `protobuf:"bytes,3,opt,name=text" json:"text,omitempty"`
	Highlight     string `protobuf:"bytes,4,opt,name=highlight" json:"highlight,omitempty"`
	HighlightText string `protobuf:"bytes,5,opt,name=highlightText" json:"highlightText,omitempty"`
}

func (m *Profile_Colors) Reset()                    { *m = Profile_Colors{} }
func (m *Profile_Colors) String() string            { return proto.CompactTextString(m) }
func (*Profile_Colors) ProtoMessage()               {}
func (*Profile_Colors) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{0, 3} }

func (m *Profile_Colors) GetPrimary() string {
	if m != nil {
		return m.Primary
	}
	return ""
}

func (m *Profile_Colors) GetSecondary() string {
	if m != nil {
		return m.Secondary
	}
	return ""
}

func (m *Profile_Colors) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *Profile_Colors) GetHighlight() string {
	if m != nil {
		return m.Highlight
	}
	return ""
}

func (m *Profile_Colors) GetHighlightText() string {
	if m != nil {
		return m.HighlightText
	}
	return ""
}

type Profile_Stats struct {
	FollowerCount  uint32  `protobuf:"varint,1,opt,name=followerCount" json:"followerCount,omitempty"`
	FollowingCount uint32  `protobuf:"varint,2,opt,name=followingCount" json:"followingCount,omitempty"`
	ListingCount   uint32  `protobuf:"varint,3,opt,name=listingCount" json:"listingCount,omitempty"`
	RatingCount    uint32  `protobuf:"varint,4,opt,name=ratingCount" json:"ratingCount,omitempty"`
	AverageRating  float32 `protobuf:"fixed32,5,opt,name=averageRating" json:"averageRating,omitempty"`
}

func (m *Profile_Stats) Reset()                    { *m = Profile_Stats{} }
func (m *Profile_Stats) String() string            { return proto.CompactTextString(m) }
func (*Profile_Stats) ProtoMessage()               {}
func (*Profile_Stats) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{0, 4} }

func (m *Profile_Stats) GetFollowerCount() uint32 {
	if m != nil {
		return m.FollowerCount
	}
	return 0
}

func (m *Profile_Stats) GetFollowingCount() uint32 {
	if m != nil {
		return m.FollowingCount
	}
	return 0
}

func (m *Profile_Stats) GetListingCount() uint32 {
	if m != nil {
		return m.ListingCount
	}
	return 0
}

func (m *Profile_Stats) GetRatingCount() uint32 {
	if m != nil {
		return m.RatingCount
	}
	return 0
}

func (m *Profile_Stats) GetAverageRating() float32 {
	if m != nil {
		return m.AverageRating
	}
	return 0
}

func init() {
	proto.RegisterType((*Profile)(nil), "Profile")
	proto.RegisterType((*Profile_Contact)(nil), "Profile.Contact")
	proto.RegisterType((*Profile_SocialAccount)(nil), "Profile.SocialAccount")
	proto.RegisterType((*Profile_Image)(nil), "Profile.Image")
	proto.RegisterType((*Profile_Colors)(nil), "Profile.Colors")
	proto.RegisterType((*Profile_Stats)(nil), "Profile.Stats")
}

func init() { proto.RegisterFile("profile.proto", fileDescriptor6) }

var fileDescriptor6 = []byte{
	// 675 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0x93, 0xcf, 0x6e, 0xd4, 0x3a,
	0x14, 0xc6, 0x35, 0xd3, 0xf9, 0xd3, 0x7a, 0x66, 0xda, 0x5e, 0xeb, 0xaa, 0xb2, 0xa2, 0x2b, 0xdd,
	0x51, 0x55, 0xc1, 0x88, 0x45, 0x8a, 0x86, 0x3d, 0x12, 0xb4, 0x0b, 0xba, 0x28, 0xaa, 0xd2, 0xb2,
	0x61, 0xe7, 0x24, 0x9e, 0xc4, 0xc2, 0xb1, 0x23, 0xdb, 0x69, 0x19, 0xf1, 0x08, 0xbc, 0x00, 0xaf,
	0xc2, 0x92, 0x37, 0x43, 0x3e, 0x76, 0x32, 0x93, 0xc2, 0xce, 0xdf, 0xef, 0x7c, 0xc7, 0x39, 0x76,
	0x3e, 0xa3, 0x45, 0xad, 0xd5, 0x86, 0x0b, 0x16, 0xd7, 0x5a, 0x59, 0x15, 0xfd, 0x5f, 0x28, 0x55,
	0x08, 0x76, 0x09, 0x2a, 0x6d, 0x36, 0x97, 0x96, 0x57, 0xcc, 0x58, 0x5a, 0xd5, 0xc1, 0x70, 0x52,
	0xa9, 0x9c, 0x69, 0x6a, 0x95, 0xf6, 0xe0, 0xfc, 0x27, 0x42, 0xd3, 0x3b, 0xbf, 0x07, 0x3e, 0x43,
	0x93, 0x9a, 0x31, 0x7d, 0x73, 0x4d, 0x06, 0xcb, 0xc1, 0xea, 0x28, 0x09, 0xca, 0xf1, 0x92, 0xca,
	0x5c, 0x30, 0x32, 0xf4, 0xdc, 0x2b, 0x8c, 0xd1, 0x48, 0xd2, 0x8a, 0x91, 0x03, 0xa0, 0xb0, 0xc6,
	0x11, 0x3a, 0x14, 0x2a, 0xa3, 0x96, 0x2b, 0x49, 0x46, 0xc0, 0x3b, 0x8d, 0xff, 0x45, 0x63, 0x9a,
	0xaa, 0xc6, 0x92, 0x31, 0x14, 0xbc, 0xc0, 0xaf, 0xd0, 0xa9, 0x29, 0x95, 0xb6, 0xd7, 0xcc, 0x64,
	0x9a, 0xd7, 0xd0, 0x39, 0x01, 0xc3, 0x1f, 0x1c, 0xbe, 0x68, 0x36, 0x4f, 0x64, 0xba, 0x1c, 0xac,
	0x0e, 0x13, 0x58, 0xbb, 0xe9, 0x1e, 0x99, 0xcc, 0x95, 0x26, 0x87, 0x40, 0x83, 0xc2, 0xff, 0xa1,
	0xa3, 0xee, 0xb0, 0xe4, 0x08, 0x4a, 0x3b, 0x80, 0x5f, 0xa3, 0x45, 0x27, 0x6e, 0xe4, 0x46, 0x11,
	0xb4, 0x1c, 0xac, 0x66, 0x6b, 0x14, 0xdf, 0xb6, 0x34, 0xe9, 0x1b, 0xf0, 0x1a, 0xcd, 0x32, 0x25,
	0x2d, 0xcd, 0x2c, 0xf8, 0x67, 0xe0, 0x3f, 0x8d, 0xc3, 0xe5, 0xc5, 0x57, 0xbe, 0x96, 0xec, 0x9b,
	0xf0, 0x4b, 0x34, 0xc9, 0x94, 0x50, 0xda, 0x90, 0x39, 0xd8, 0x4f, 0xf6, 0xec, 0x0e, 0x27, 0xa1,
	0x8c, 0xd7, 0x68, 0x4e, 0x1f, 0xa9, 0xa5, 0xfa, 0x03, 0x35, 0x25, 0x33, 0x64, 0x01, 0xf6, 0xe3,
	0xce, 0x7e, 0x53, 0xd1, 0x82, 0x25, 0x3d, 0x8f, 0xeb, 0x29, 0x19, 0xcd, 0x59, 0xdb, 0x73, 0xfc,
	0xf7, 0x9e, 0x7d, 0x0f, 0xbe, 0x40, 0x63, 0x63, 0xa9, 0x35, 0xe4, 0xe4, 0x99, 0xf9, 0xde, 0xd1,
	0xc4, 0x17, 0xf1, 0x05, 0x5a, 0xa4, 0xdc, 0x66, 0x8a, 0xcb, 0xbb, 0x26, 0xfd, 0xc2, 0xb6, 0xe4,
	0x14, 0xfe, 0x47, 0x1f, 0xe2, 0xb7, 0x68, 0x2e, 0xa8, 0xb1, 0xb7, 0x2a, 0xe7, 0x1b, 0xce, 0x72,
	0xf2, 0x0f, 0x6c, 0x19, 0xc5, 0x3e, 0x83, 0x71, 0x9b, 0xc1, 0xf8, 0xa1, 0xcd, 0x60, 0xd2, 0xf3,
	0x47, 0xdf, 0x07, 0x68, 0x1a, 0x6e, 0x0d, 0x13, 0x34, 0x7d, 0x62, 0xa9, 0xe1, 0x96, 0x85, 0xec,
	0xb5, 0xd2, 0x85, 0x86, 0x55, 0x94, 0x8b, 0x90, 0x3d, 0x2f, 0xf0, 0x12, 0xcd, 0xea, 0x52, 0x49,
	0xf6, 0xb1, 0xa9, 0x52, 0xa6, 0x43, 0x02, 0xf7, 0x11, 0x8e, 0xd1, 0xc4, 0xa8, 0x8c, 0x53, 0x41,
	0x46, 0xcb, 0x83, 0xd5, 0x6c, 0x7d, 0xb6, 0x3b, 0x2a, 0xe0, 0x77, 0x59, 0xa6, 0x1a, 0x69, 0x93,
	0xe0, 0x8a, 0x3e, 0xa1, 0x45, 0xaf, 0xe0, 0xb2, 0x66, 0xb7, 0x75, 0x3b, 0x0f, 0xac, 0x5d, 0xba,
	0x1b, 0xc3, 0x34, 0xa4, 0xde, 0xcf, 0xd3, 0x69, 0x37, 0x68, 0xad, 0x95, 0xda, 0x84, 0x61, 0xbc,
	0x88, 0xbe, 0xa1, 0x31, 0xfc, 0x07, 0xd8, 0x8e, 0xcb, 0x6d, 0xb7, 0x1d, 0x97, 0x5b, 0xd7, 0x62,
	0x2a, 0x2a, 0xba, 0xb3, 0x81, 0x70, 0x81, 0xae, 0x58, 0xce, 0x9b, 0x2a, 0xec, 0x14, 0x94, 0x73,
	0x0b, 0xaa, 0x0b, 0x16, 0xde, 0x95, 0x17, 0x6e, 0x24, 0xa5, 0x79, 0xc1, 0x25, 0x15, 0xe1, 0x5d,
	0x75, 0x3a, 0xfa, 0x31, 0x40, 0x13, 0x1f, 0x34, 0x77, 0xc1, 0xb5, 0xe6, 0x15, 0xd5, 0xed, 0x04,
	0xad, 0x74, 0xef, 0xc4, 0xb0, 0x4c, 0xc9, 0xdc, 0xd5, 0xfc, 0x20, 0x3b, 0x00, 0x63, 0xb3, 0xaf,
	0xb6, 0x7d, 0xe3, 0x6e, 0xed, 0x3a, 0x4a, 0x5e, 0x94, 0x82, 0x17, 0xa5, 0x0d, 0xc3, 0xec, 0x80,
	0x0b, 0x4f, 0x27, 0x1e, 0x5c, 0xab, 0x9f, 0xaa, 0x0f, 0xa3, 0x5f, 0x03, 0x34, 0xbe, 0x6f, 0xc3,
	0xb6, 0x51, 0x42, 0xa8, 0x27, 0xa6, 0xaf, 0xdc, 0xc5, 0xc3, 0x7c, 0x8b, 0xa4, 0x0f, 0xf1, 0x0b,
	0x74, 0xec, 0x01, 0x97, 0x85, 0xb7, 0x0d, 0xc1, 0xf6, 0x8c, 0xe2, 0x73, 0x34, 0x17, 0xdc, 0xd8,
	0xce, 0x75, 0x00, 0xae, 0x1e, 0x73, 0xe1, 0xd1, 0x74, 0x67, 0x19, 0x81, 0x65, 0x1f, 0xb9, 0x99,
	0xe8, 0x23, 0xd3, 0xee, 0xfd, 0x00, 0x85, 0x33, 0x0c, 0x93, 0x3e, 0x7c, 0x3f, 0xfa, 0x3c, 0xac,
	0xd3, 0x74, 0x02, 0x41, 0x7f, 0xf3, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x33, 0xea, 0x2f, 0x1b, 0x8b,
	0x05, 0x00, 0x00,
}
