
// Objective-C API for talking to the following Go packages
//
//	github.com/OpenBazaar/openbazaar-go
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Openbazaar_FRAMEWORK_H__
#define __Openbazaar_FRAMEWORK_H__

#include "Openbazaar.objc.h"
#include "Universe.objc.h"

#endif
